(function(){function n(c){var e=0;return function(){return e<c.length?{done:!1,value:c[e++]}:{done:!0}}}var p="function"==typeof Object.create?Object.create:function(c){function e(){}e.prototype=c;return new e},q;if("function"==typeof Object.setPrototypeOf)q=Object.setPrototypeOf;else{var r;a:{var t={ka:!0},v={};try{v.__proto__=t;r=v.ka;break a}catch(c){}r=!1}q=r?function(c,e){c.__proto__=e;if(c.__proto__!==e)throw new TypeError(c+" is not extensible");return c}:null}var w=q;
function x(c,e){c.prototype=p(e.prototype);c.prototype.constructor=c;if(w)w(c,e);else for(var a in e)if("prototype"!=a)if(Object.defineProperties){var b=Object.getOwnPropertyDescriptor(e,a);b&&Object.defineProperty(c,a,b)}else c[a]=e[a];c.ua=e.prototype}var y="function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,a){c!=Array.prototype&&c!=Object.prototype&&(c[e]=a.value)},z="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function A(c,e){if(e){var a=z;c=c.split(".");for(var b=0;b<c.length-1;b++){var d=c[b];d in a||(a[d]={});a=a[d]}c=c[c.length-1];b=a[c];e=e(b);e!=b&&null!=e&&y(a,c,{configurable:!0,writable:!0,value:e})}}var B="function"==typeof Object.assign?Object.assign:function(c,e){for(var a=1;a<arguments.length;a++){var b=arguments[a];if(b)for(var d in b)Object.prototype.hasOwnProperty.call(b,d)&&(c[d]=b[d])}return c};A("Object.assign",function(c){return c||B});
(function(){function c(e,a,b){function d(g,h){if(!a[g]){if(!e[g]){var l="function"==typeof require&&require;if(!h&&l)return l(g,!0);if(f)return f(g,!0);h=Error("Cannot find module '"+g+"'");throw h.code="MODULE_NOT_FOUND",h;}h=a[g]={g:{}};e[g][0].call(h.g,function(b){return d(e[g][1][b]||b)},h,h.g,c,e,a,b)}return a[g].g}for(var f="function"==typeof require&&require,g=0;g<b.length;g++)d(b[g]);return d}return c})()({1:[function(c,e){e.g={beaconEndpoint:"https://metrics-collector.s-onetag.com/metrics",
cookieEndpoint:"https://ap.lijit.com/readerinfo/v2",geoLocationUrl:"//onetag-geo.s-onetag.com/",geoGroupingUrl:"//onetag-geo-grouping.s-onetag.com/",geoDetectionUrl:"https://geo-location.s-onetag.com/",geoLocationCacheTtl:86400,noTrackingGeoGroup:"EU",disengagementThreshold:10,sovrnVendorId:13}},{}],2:[function(c,e){var a=c(3),b=c(5),d=c(6);e.g=function(f,c){var g=new b(f);c=new d(f,c);return new a(g,c,f)}},{3:3,5:5,6:6}],3:[function(c,e){function a(b,d,a){this.b=b;this.h=d;this.a={};this.f=[];this.i=
[];this.c=[];this.window=a;this.m=!1}a.prototype.start=function(){this.m||(this.m=!0,this.b.ea(this.l.bind(this)),this.b.start(),this.h.ea(this.l.bind(this)),this.h.start(),this.f.push(this.b),this.f.push(this.h),this.i.push(this.b),this.c.push(this.h),this.c.push(this.b))};a.prototype.M=function(b,d){"undefined"===typeof this.a[b]&&(this.a[b]=[]);this.a[b].push(d)};a.prototype.l=function(b,d,a){this.j(b,{name:b});d&&this.A()?(b="user_active",this.j(b,{name:b}),this.H()):!d&&this.B(a.id)&&(b="user_inactive",
this.j(b,{name:b}))};a.prototype.H=function(){for(var b=this.f.length;b--;)this.f[b].reset()};a.prototype.A=function(){for(var b=this.i.length;b--;)if(!this.i[b].u)return!1;return!0};a.prototype.B=function(b){for(var d=this.c.length;d--;)if(this.c[d].id===b)return!0;return!1};a.prototype.j=function(b,d){if(this.a[b])for(var a=this.a[b].length;a--;)this.a[b][a](d)};e.g=a},{}],4:[function(c,e){function a(b){this.id=b;this.u=!0;this.a=null}a.prototype.ea=function(b){this.a=b};a.prototype.G=function(b,
d){this.a(this.id+"_"+b,d,this)};a.prototype.C=function(b,d,a){function f(b){a(b)}b.addEventListener?b.addEventListener(d,f.bind(this),!1):b.attachEvent("on"+d,f.bind(this))};a.prototype.reset=function(){this.u=!0};e.g=a},{}],5:[function(c,e){function a(d){var a=b.call(this,"focus")||this;a.window=d;return a}var b=c(4);x(a,b);a.prototype.start=function(){this.C(this.window,"focus",this.X.bind(this));this.C(this.window,"focusin",this.X.bind(this));this.C(this.window,"blur",this.W.bind(this));this.C(this.window,
"focusout",this.W.bind(this))};a.prototype.X=function(){this.u=!0;this.G("active",!0)};a.prototype.W=function(){if(this.window.document.hasFocus())return this.G("active",!0);this.G("inactive",!1)};e.g=a},{4:4}],6:[function(c,e){function a(d,a){var f=b.call(this,"input")||this;f.ba=!1;f.sa=a||10;f.fa="mousemove mousedown scroll keyup keypress keydown touchstart touchmove touchend".split(" ");f.window=d;return f}var b=c(4);x(a,b);a.prototype.start=function(){for(var b=0;b<this.fa.length;b++)this.C(this.window,
this.fa[b],this.O.bind(this));this.ba||(this.ba=!0,this.O())};a.prototype.O=function(){this.u||this.G("active",!0);clearTimeout(this.ta);this.ta=setTimeout(this.la.bind(this),1E3*this.sa);this.u=!0};a.prototype.la=function(){this.u&&this.G("inactive",!1);this.u=!1};a.prototype.reset=function(){b.prototype.reset.call(this);this.O()};e.g=a},{4:4}],7:[function(c,e){c=c(8);e.g=c},{8:8}],8:[function(c,e){function a(b){this.a=b.config;this.b=b.httpClient;this.window=b.window;this.h=!1;this.f=[]}a.prototype.na=
function(b){var d=this;this.D(function(a){d.j(function(d){return a?0===d.length?b({message:"Grouping not found"},null):b(null,-1<d.indexOf(a)):b({message:"Location not found"},null)})})};a.prototype.D=function(b){var d=this,a=this.c("underground-location");a?b(a):(this.f.push(b),this.h||(this.h=!0,this.b.get(this.a.geoLocationUrl,function(b){var a=b.country;a&&d.i("underground-location",a);d.f.forEach(function(b){return b(a)});d.f=[];d.h=!1})))};a.prototype.oa=function(b){var d=this,a=this.c("underground-us-state-location");
if(a)return b(null,"CA"===a);this.b.get(this.a.geoDetectionUrl,function(a){if(!a)return b({message:"Location not found"},null);d.i("underground-us-state-location",a.state);"CA"===a.state?b(null,!0):b(null,!1)})};a.prototype.i=function(b,d){d={value:d,expiresAt:Date.now()+1E3*this.a.geoLocationCacheTtl};try{this.window.localStorage.setItem(b,JSON.stringify(d))}catch(f){}};a.prototype.c=function(b){try{var d=JSON.parse(this.window.localStorage.getItem(b));return d.expiresAt>Date.now()?d.value:!1}catch(f){return!1}};
a.prototype.j=function(b){var d=this,a=this.c("underground-grouping_EU");a?b(a):this.b.get(this.a.geoGroupingUrl+"regionalbloc/EU",function(a){var f=[];a.countries&&(f=a.countries.map(function(b){return b.code}),d.i("underground-grouping_EU",f));return b(f)})};e.g=a},{}],9:[function(c,e){c=c(10);e.g=c},{10:10}],10:[function(c,e){function a(){this.a=new b}var b=c(11);a.prototype.qa=function(b,a,c){var d=this.a.create();d.open("POST",b,c?!1:!0);d.setRequestHeader("Content-Type","text/plain");d.send(JSON.stringify(a))};
a.prototype.get=function(b,a,c){var d=this.a.create();d.onreadystatechange=function(){if(4===d.readyState){try{var b=JSON.parse(d.responseText)}catch(u){b={}}a(b)}};d.open("GET",b,!0);d.withCredentials=!!c;d.send()};e.g=a},{11:11}],11:[function(c,e){function a(){}a.prototype.create=function(){return new XMLHttpRequest};e.g=a},{}],12:[function(c,e){c=c(13);e.g=c},{13:13}],13:[function(c,e){function a(b,d){this.b=d;this.window=b}a.prototype.ma=function(b){if(this.window.ja&&"SAFEFRAME"===this.window.ja.state)return this.window.$sf.ext.inViewPercentage()/
100>=this.b;b=b.getBoundingClientRect();return this.f(b,this.window.innerWidth)*this.c(b,this.window.innerHeight)/(b.width*b.height)>=this.b};a.prototype.f=function(b,d){return this.a(b.right,d)-this.a(b.left,d)};a.prototype.c=function(b,d){return this.a(b.bottom,d)-this.a(b.top,d)};a.prototype.a=function(b,d){return Math.max(0,Math.min(b,d))};e.g=a},{}],14:[function(c,e){function a(b){this.window=b}var b=c(17),d=c(2),f=c(15),g=c(7),l=c(9),h=c(21),u=c(24),C=c(16),D=c(22),E=c(23),F=c(12),G=c(25),m=
c(1);a.prototype.load=function(){if(!this.c()){var b=(new G(this.window)).parse(),d=this.a(b.isLightMode,b.percentInView||.5);d.start(b.containerId,b.doNotTrack);this.b(d)}};a.prototype.a=function(a,c){var e=new d(this.window,m.disengagementThreshold),k=new l;c={window:this.window,config:m,viewability:new F(this.window,c),engagementMonitor:e,httpClient:k};e=new g(c);c.consentProvider=new f(this.window,e,m);c.geoLocationService=e;e=new C(this.window,k,m);k=new h(this.window);e=new u(this.window,e,
c);if(a)return a=new E(c,e,k),new b(c,a);a=new D(c,e,k);return new b(c,a)};a.prototype.c=function(){return this.window.__connect.beacon&&this.window.__connect.beacon.trackSelector?!0:!1};a.prototype.b=function(b){var d={};this.window.__connect.beacon&&(d=this.window.__connect.beacon.settings||{});this.window.__connect.beacon={trackSelector:b.ga.bind(b),settings:d}};e.g=a},{1:1,12:12,15:15,16:16,17:17,2:2,21:21,22:22,23:23,24:24,25:25,7:7,9:9}],15:[function(c,e){function a(b,d,a){this.window=b;this.a=
d;this.b=a}a.prototype.Y=function(b){var d=this;this.a.D(function(a){if(!a)return b({message:"Location not found"},null);if("US"===a)return d.a.oa(d.j.bind(d,b));d.a.na(d.i.bind(d,b))})};a.prototype.pa=function(b){var d=this;this.Y(function(a,c){return a?b(!1):"gdpr"===c?d.f(b):"usp"===c?d.h(b):b(!0)})};a.prototype.aa=function(b,d){return this.c(void 0===d?null:d,b)};a.prototype.j=function(b,d,a){if(d||a)return b(null,"usp");b(null,null)};a.prototype.i=function(b,d,a){if(d||a)return b(null,"gdpr");
b(null,null)};a.prototype.f=function(b){var a=this.b.sovrnVendorId;return this.aa(function(d){return d.vendorConsents?b(d.vendorConsents[a]):b(d)},[a])};a.prototype.h=function(b){var a=this.window.__uspapi;if(!a||"function"!==typeof a)return b(!1);a("getUSPData",1,function(a,d){if(!a||!d)return b(!1);if(-1<["1YN-","1YNN","1YNY"].indexOf(a.uspString))return b(!0);b(!1)})};a.prototype.c=function(b,a){function d(b){d.a||(d.a=!0,a(b),clearTimeout(e))}var c=this.window.__cmp;if(!c||"function"!==typeof c)return a(!1);
var e=null;e=setTimeout(function(){d(!1)},2E3);c("ping",null,function(b){b.cmpLoaded||d(!1)});c("getVendorConsents",b,function(a){if(a)return d(a);c("addEventListener","onSubmit",function(){c("getVendorConsents",b,function(b){return d(b)})})})};e.g=a},{}],16:[function(c,e){function a(b,a,c){this.window=b;this.c=a;this.b=c;this.a=null}a.prototype.get=function(b){var a=this;this.a?b(this.a):this.c.get(this.b.cookieEndpoint,function(d){a.a=d.ljt_reader;b(a.a)},!0)};e.g=a},{}],17:[function(c,e){function a(b,
a){this.b=b.engagementMonitor;this.H=b.httpClient;this.m=b.config;this.window=b.window;this.j=this.l=!0;this.a=a;this.h=null}a.prototype.start=function(b,a){this.a.start(b,a);this.h=this.a.$();this.b.start();this.b.M("user_active",this.L.bind(this));this.b.M("user_inactive",this.ia.bind(this));this.b.M("session_leaving",this.f.bind(this,!0));this.a.da(this.f.bind(this));this.B()};a.prototype.B=function(){this.i=this.window.setInterval(this.K.bind(this),1E3)};a.prototype.K=function(){this.a.ha(this.l)};
a.prototype.ga=function(b,a){var d=this.U(this.window.document.querySelector(b));this.J(b,a,d)&&this.a.ca(b,a,d)};a.prototype.J=function(b,a,c){var d=this;return c?!0:(setTimeout(function(){d.ga(b,a)},1E3),!1)};a.prototype.U=function(b){b=b.getElementsByTagName("iframe");for(var a=0;a<b.length;a++){var c=b[a].getBoundingClientRect();if(c.width&&c.height)return c}};a.prototype.L=function(){this.c&&(this.window.clearTimeout(this.c),this.c=0);this.i||this.B();this.j=this.l=!0};a.prototype.ia=function(){this.l=
!1;this.j&&this.f(!1);this.j=!1;this.c||(this.c=this.window.setTimeout(this.T.bind(this),3E5))};a.prototype.T=function(){this.f(!1);this.window.clearInterval(this.i);this.i=0};a.prototype.f=function(b){var a=this,c={metadata:this.h,payloads:this.a.Z()};this.a.o();if(b)return this.A(c,!0);this.a.getMetadata(function(b){a.h=b;c.metadata=b;a.A(c,!1)})};a.prototype.A=function(b,a){var d=this.window.navigator,c=!1;d.sendBeacon&&(c=d.sendBeacon(this.m.beaconEndpoint,JSON.stringify(b)));c||this.H.qa(this.m.beaconEndpoint,
b,a)};e.g=a},{}],18:[function(c,e){function a(b,a){this.window=b;this.s=a.s;this.v=a.v;this.type="LIGHT";this.b=0;this.a=1}a.prototype.F=function(){return{type:this.type,selector:this.v,contentId:this.s,refreshes:this.b,impressions:this.a}};a.prototype.R=function(){this.b+=1;this.a+=1};a.prototype.o=function(){this.a=this.b=0};e.g=a},{}],19:[function(c,e){function a(b){this.window=b;this.type="PAGE";this.c=this.b=this.a=0;this.f=null}a.prototype.F=function(){return{type:this.type,dwellTime:this.a,
engagedDwellTime:this.b,scrollDepth:this.c,cmpMetrics:this.f}};a.prototype.P=function(){this.b+=1};a.prototype.S=function(){this.a+=1;this.c=Math.max(this.c,this.window.pageYOffset)};a.prototype.o=function(){this.b=this.a=0};a.prototype.ra=function(b){this.f=b};e.g=a},{}],20:[function(c,e){function a(b,a){this.v=a.v;this.s=a.s;this.w=a.w;this.window=b;this.type="PLACEMENT";this.c=this.f=0;this.a=1;this.h=this.b=0}a.prototype.F=function(){var b=this.i();return{type:this.type,secondsInView:this.c,viewableEngagedTime:this.f,
dimensions:b,aboveTheFold:this.j(b),refreshes:this.b,impressions:this.a,selector:this.v,contentId:this.s,dwellTime:this.h}};a.prototype.i=function(){return{top:this.w.top+this.window.scrollY,left:this.w.left+this.window.scrollX,height:this.w.height,width:this.w.width}};a.prototype.P=function(b){b&&(this.f+=1)};a.prototype.S=function(b){b&&(this.c+=1);this.h+=1};a.prototype.o=function(){this.b=this.a=this.c=this.f=0};a.prototype.R=function(){this.b+=1;this.a+=1};a.prototype.j=function(b){return 0<=
this.window.innerHeight-(b.height/2+b.top)};e.g=a},{}],21:[function(c,e){function a(a){this.window=a;this.a={Placement:f,Page:d,Light:b}}var b=c(18),d=c(19),f=c(20);a.prototype.create=function(b,a){return new this.a[b](this.window,a)};e.g=a},{18:18,19:19,20:20}],22:[function(c,e){function a(b,a,c){this.window=b.window;this.L=b.viewability;this.h=b.consentProvider;this.a={};this.c=a;this.i=c;this.b=this.i.create("Page");this.containerId=null;this.j=function(){};this.f=null}a.prototype.start=function(b,
a){this.containerId=b;a&&this.c.V()};a.prototype.ca=function(b,a,c){var d=this.a[b];d&&(d.va=null);this.A(d,a)&&this.j();this.J(d,a)?d.metrics.R():this.m(b,a,c)};a.prototype.m=function(b,a,c){var d=this.window.document.querySelector(b);c=this.i.create("Placement",{v:b,s:a,w:c});this.a[b]={selector:b,element:d,contentId:a,metrics:c}};a.prototype.A=function(b,a){return b&&b.contentId!==a};a.prototype.J=function(b,a){return b&&b.contentId===a};a.prototype.da=function(b){this.j=b};a.prototype.ha=function(b){b&&
this.b.P();this.b.S();this.K(b)};a.prototype.K=function(b){for(var a in this.a)if(this.a.hasOwnProperty(a)){var c=this.a[a],e=c.metrics;c=this.L.ma(this.T(c));b&&e.P(c);e.S(c)}};a.prototype.T=function(b){if(!b.I||!this.U(b)){var a=this.l(b.element,"iframe");b.I=a||this.l(b.element,"img")}return b.I?b.I:b.element};a.prototype.U=function(b){for(var a=b.I;a.parentNode;)if(a=a.parentNode,a===b.element)return!0;return!1};a.prototype.l=function(b,a){b=b.getElementsByTagName(a);for(a=0;a<b.length;a++){var d=
b[a].getBoundingClientRect();if(d.width&&d.height)return b[a]}};a.prototype.o=function(){for(var b in this.a)this.a.hasOwnProperty(b)&&this.a[b].metrics.o();this.b.o()};a.prototype.Z=function(){this.B();var b=[this.b.F()],a;for(a in this.a)this.a.hasOwnProperty(a)&&b.push(this.a[a].metrics.F());return b};a.prototype.B=function(){var b=this;this.f||this.h.Y(function(a,c){"gdpr"!==c?b.f=!0:b.h.aa(function(a){a&&(b.b.ra(b.H(a)),b.f=!0)})})};a.prototype.getMetadata=function(b){return this.c.get(this.containerId,
function(a){return b(a)})};a.prototype.$=function(){return this.c.N(this.containerId)};a.prototype.H=function(b){var a=b.vendorConsents,c=Object.keys(a),e=c.reduce(function(b,d){a[d]&&b++;return b},0);return{consentString:b.metadata,cmpId:b.cmpId,globalCookie:b.hasGlobalScope,numberOfVendors:c.length,numberOfConsentedVendors:e}};e.g=a},{}],23:[function(c,e){function a(b,a,c){this.b=a;this.f=c;this.a={};this.c=function(){}}a.prototype.start=function(b){this.containerId=b;this.b.V()};a.prototype.ca=
function(b,a){var d=this.a[b];!d||this.i(d,a)?this.h(b,a):d.metrics.R();this.c()};a.prototype.h=function(b,a){var d=this.f.create("Light",{v:b,s:a});this.a[b]={selector:b,contentId:a,metrics:d}};a.prototype.i=function(b,a){return b&&b.contentId!==a};a.prototype.da=function(b){this.c=b};a.prototype.o=function(){for(var b in this.a)this.a.hasOwnProperty(b)&&this.a[b].metrics.o()};a.prototype.Z=function(){var b=[],a;for(a in this.a)this.a.hasOwnProperty(a)&&b.push(this.a[a].metrics.F());return b};a.prototype.getMetadata=
function(b){return this.b.get(this.containerId,function(a){return b({pageViewSalt:a.pageViewSalt,url:a.url,containerId:a.containerId})})};a.prototype.$=function(){var b=this.b.N(this.containerId);return{pageViewSalt:b.pageViewSalt,url:b.url,containerId:b.containerId}};a.prototype.ha=function(){};e.g=a},{}],24:[function(c,e){function a(b,a,c){this.window=b;this.m=this.h();this.f=a;this.a=!0;this.c=c.geoLocationService;this.b=c.consentProvider}a.prototype.get=function(b,a){var d=this,c=this.N(b);this.D(function(b){c.location=
b;if(!d.a)return a(c);d.l(function(b){c.ljtReader=b;return a(c)})})};a.prototype.N=function(b){return{pageViewSalt:this.m,screenWidth:this.window.screen.width,screenHeight:this.window.screen.height,documentHeight:this.j(),url:this.window.location.href,containerId:b,ljtReader:"",location:""}};a.prototype.l=function(b){var a=this;this.b.pa(function(c){return c?a.i(b):b("")})};a.prototype.i=function(b){return this.f.get(b)};a.prototype.D=function(b){this.c.D(b)};a.prototype.h=function(){return+new Date+
Math.floor(1E3*Math.random())};a.prototype.j=function(){var b=this.window.document.body,a=this.window.document.documentElement;return b?Math.max(b.scrollHeight,b.offsetHeight,a.clientHeight,a.scrollHeight,a.offsetHeight):0};a.prototype.V=function(){this.a=!1};e.g=a},{}],25:[function(c,e){function a(b){this.window=b}a.prototype.a=function(){return this.window.__connect.beacon?this.window.__connect.beacon.settings:{}};a.prototype.b=function(){if(!this.window.document.currentScript)return{};var b=this.window.document.currentScript.src,
a=b.indexOf("?"),c={};if(-1===a)return{};b=b.slice(a+1).split("&");b=(a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator])?a.call(b):{next:n(b)};for(a=b.next();!a.done;a=b.next())a=a.value.split("="),c[a[0]]=a[1];return c};a.prototype.parse=function(){var a=this.window.navigator.doNotTrack||this.window.doNotTrack,c=Object.assign(this.a(),this.b());return{percentInView:c.percentInView,containerId:c.containerId,doNotTrack:c.doNotTrack||a,isLightMode:c.isLightMode||!1}};e.g=a},{}],26:[function(c){var e=
window.top;e.__connect=e.__connect||{};(new (c(14))(e)).load()},{14:14}]},{},[26]);}).call(this);
