(function(){var t="function"==typeof Object.create?Object.create:function(d){function f(){}f.prototype=d;return new f},x;if("function"==typeof Object.setPrototypeOf)x=Object.setPrototypeOf;else{var A;a:{var B={Ra:!0},C={};try{C.__proto__=B;A=C.Ra;break a}catch(d){}A=!1}x=A?function(d,f){d.__proto__=f;if(d.__proto__!==f)throw new TypeError(d+" is not extensible");return d}:null}var D=x;
function L(d,f){d.prototype=t(f.prototype);d.prototype.constructor=d;if(D)D(d,f);else for(var b in f)if("prototype"!=b)if(Object.defineProperties){var a=Object.getOwnPropertyDescriptor(f,b);a&&Object.defineProperty(d,b,a)}else d[b]=f[b];d.Ob=f.prototype}var M="function"==typeof Object.defineProperties?Object.defineProperty:function(d,f,b){d!=Array.prototype&&d!=Object.prototype&&(d[f]=b.value)},N="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function O(){O=function(){};N.Symbol||(N.Symbol=P)}var P=function(){var d=0;return function(f){return"jscomp_symbol_"+(f||"")+d++}}();function Q(){O();var d=N.Symbol.iterator;d||(d=N.Symbol.iterator=N.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&M(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return R(this)}});Q=function(){}}function R(d){var f=0;return T(function(){return f<d.length?{done:!1,value:d[f++]}:{done:!0}})}
function T(d){Q();d={next:d};d[N.Symbol.iterator]=function(){return this};return d}function U(d){Q();O();Q();var f=d[Symbol.iterator];return f?f.call(d):R(d)}function V(d){for(var f,b=[];!(f=d.next()).done;)b.push(f.value);return b}function W(d,f){if(f){var b=N;d=d.split(".");for(var a=0;a<d.length-1;a++){var c=d[a];c in b||(b[c]={});b=b[c]}d=d[d.length-1];a=b[d];f=f(a);f!=a&&null!=f&&M(b,d,{configurable:!0,writable:!0,value:f})}}
W("Array.prototype.find",function(d){return d?d:function(d,b){a:{var a=this;a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var g=a[e];if(d.call(b,g,e,a)){d=g;break a}}d=void 0}return d}});var X="function"==typeof Object.assign?Object.assign:function(d,f){for(var b=1;b<arguments.length;b++){var a=arguments[b];if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(d[c]=a[c])}return d};W("Object.assign",function(d){return d||X});
(function(){function d(f,b,a){function c(g,h){if(!b[g]){if(!f[g]){var m="function"==typeof require&&require;if(!h&&m)return m(g,!0);if(e)return e(g,!0);h=Error("Cannot find module '"+g+"'");throw h.code="MODULE_NOT_FOUND",h;}h=b[g]={g:{}};f[g][0].call(h.g,function(a){return c(f[g][1][a]||a)},h,h.g,d,f,b,a)}return b[g].g}for(var e="function"==typeof require&&require,g=0;g<a.length;g++)c(a[g]);return c}return d})()({1:[function(d,f){function b(a,c){this.b=a;this.a=c}b.prototype.rb=function(a){var c=
this.c(),e=this.a.min;a(c<=this.a.max&&c>=e)};b.prototype.c=function(){return this.b.window.innerWidth};f.g=b},{}],2:[function(d,f){f.g={config:{executeImmediately:!1},contentFunction:function(b,a,c){b.settings.iv="vet";a.postbidFactory.create(b,a,c).D()}}},{}],3:[function(d,f){f.g=d(4)},{4:4}],4:[function(d,f){function b(a,c){this.window=a;this.a=c}b.prototype.vb=function(a,c){this.window.__connect=this.window.__connect||{};this.window.__connect.beacon=this.window.__connect.beacon||{};this.window.__connect.beacon.settings=
{containerId:a.containerId,doNotTrack:a.doNotTrack,percentInView:a.percentInView,isLightMode:!!a.isLightMode};a=this.window.document.createElement("script");a.onload=c;a.src=this.a.beaconUrl;this.window.document.head.appendChild(a)};b.prototype.pa=function(a,c){var e=this;if(this.window.__connect&&this.window.__connect.beacon){var b=this.window.__connect.beacon;b.trackSelector?b.trackSelector(a,c):setTimeout(function(){e.pa(a,c)},100)}};f.g=b},{}],5:[function(d,f){d=d(6);f.g=d},{6:6}],6:[function(d,
f){function b(a){this.window=a;this.document=this.window.document;this.u=0;this.a={before:this.f.bind(this),after:this.b.bind(this),append:this.c.bind(this),prepend:this.i.bind(this)}}b.prototype.D=function(a,c,e,b){var g=c.settings||{},d=this.$(g.selector||"body"),f=null,p=e.adSizeService.za(g);g.width=p.width;g.height=p.height;if(!b.executeImmediately){if(!d)return;f=this.l(g,d,c)}a(c,e,f)};b.prototype.l=function(a,c,e){var b=a.method||"append",d=this.o(a.width,a.height,a.customCSS||{});this.s(c,
d,b);"onetag-vet-content"===e.type&&this.m(a.height,c);return d};b.prototype.o=function(a,c,e){var b=this.document.createElement("div");b.setAttribute("class","sovrn-onetag-ad");b.setAttribute("id","onetag-wrapper-"+this.u++);b.style.width=a+"px";b.style.height=c+"px";b.style.margin="0 auto";this.j(e,b);return b};b.prototype.s=function(a,c,e){this.a[e](a,c)};b.prototype.m=function(a,c){a=(c.getBoundingClientRect().height-a)/2;c.style.paddingTop=a+"px";c.style.paddingBottom=a+"px"};b.prototype.$=function(a){try{var c=
this.document.querySelector(a)}catch(e){this.window.console.log("Sovrn OneTag Error:",e.message)}return c};b.prototype.j=function(a,c){Object.keys(a).forEach(function(e){c.style[e]=a[e]})};b.prototype.i=function(a,c){a.insertBefore(c,a.firstChild)};b.prototype.c=function(a,c){a.appendChild(c)};b.prototype.f=function(a,c){a.parentNode.insertBefore(c,a)};b.prototype.b=function(a,c){a.parentNode.insertBefore(c,a.nextSibling)};f.g=b},{}],7:[function(d,f){var b=d(8),a=d(10),c=d(11),e=d(12);f.g=function(g,
d){var f=new a(g);d=new c(g,d);var m=new e(g);return new b(f,d,m,g)}},{10:10,11:11,12:12,8:8}],8:[function(d,f){function b(a,c,e,b){this.b=a;this.i=c;this.s=e;this.a={};this.f=[];this.l=[];this.c=[];this.window=b;this.o=!1}b.prototype.start=function(){this.o||(this.o=!0,this.s.oa(this.j.bind(this)),this.s.start(),this.b.oa(this.j.bind(this)),this.b.start(),this.i.oa(this.j.bind(this)),this.i.start(),this.f.push(this.b),this.f.push(this.i),this.l.push(this.b),this.c.push(this.i),this.c.push(this.b))};
b.prototype.sa=function(a,c){"undefined"===typeof this.a[a]&&(this.a[a]=[]);this.a[a].push(c)};b.prototype.j=function(a,c,e){this.m(a);c&&this.u()?(this.m("user_active"),this.v()):!c&&this.A(e.id)&&this.m("user_inactive")};b.prototype.v=function(){for(var a=this.f.length;a--;)this.f[a].reset()};b.prototype.u=function(){for(var a=this.l.length;a--;)if(!this.l[a].O)return!1;return!0};b.prototype.A=function(a){for(var c=this.c.length;c--;)if(this.c[c].id===a)return!0;return!1};b.prototype.m=function(a){if(this.a[a])for(var c=
this.a[a].length;c--;)this.a[a][c](void 0)};f.g=b},{}],9:[function(d,f){function b(a){this.id=a;this.O=!0;this.a=null}b.prototype.oa=function(a){this.a=a};b.prototype.P=function(a,c){this.a(this.id+"_"+a,c,this)};b.prototype.N=function(a,c,e){function b(a){e(a)}a.addEventListener?a.addEventListener(c,b.bind(this),!1):a.attachEvent("on"+c,b.bind(this))};b.prototype.reset=function(){this.O=!0};f.g=b},{}],10:[function(d,f){function b(c){var e=a.call(this,"focus")||this;e.window=c;return e}var a=d(9);
L(b,a);b.prototype.start=function(){this.N(this.window,"focus",this.va.bind(this));this.N(this.window,"focusin",this.va.bind(this));this.N(this.window,"blur",this.ua.bind(this));this.N(this.window,"focusout",this.ua.bind(this))};b.prototype.va=function(){this.O=!0;this.P("active",!0)};b.prototype.ua=function(){if(this.window.document.hasFocus())return this.P("active",!0);this.P("inactive",!1)};f.g=b},{9:9}],11:[function(d,f){function b(c,e){var b=a.call(this,"input")||this;b.Ca=!1;b.Ib=e||10;b.Ka=
"mousemove mousedown scroll keyup keypress keydown touchstart touchmove touchend".split(" ");b.window=c;return b}var a=d(9);L(b,a);b.prototype.start=function(){for(var a=0;a<this.Ka.length;a++)this.N(this.window,this.Ka[a],this.ka.bind(this));this.Ca||(this.Ca=!0,this.ka())};b.prototype.ka=function(){this.O||this.P("active",!0);clearTimeout(this.Kb);this.Kb=setTimeout(this.ob.bind(this),1E3*this.Ib);this.O=!0};b.prototype.ob=function(){this.O&&this.P("inactive",!1);this.O=!1};b.prototype.reset=function(){a.prototype.reset.call(this);
this.ka()};f.g=b},{9:9}],12:[function(d,f){function b(c){var e=a.call(this,"session")||this;e.window=c;e.Jb=2E3;e.ha=!1;return e}var a=d(9);L(b,a);b.prototype.start=function(){this.N(this.window,"pagehide",this.La.bind(this));this.N(this.window,"beforeunload",this.La.bind(this))};b.prototype.La=function(){this.ha||(this.ha=!0,this.P("leaving",!1),this.Fb())};b.prototype.Fb=function(){var a=this;setTimeout(function(){a.ha=!1},this.Jb)};f.g=b},{9:9}],13:[function(d,f){var b=d(14),a=d(15);f.g=function(c,
e){c=new a(c,e);return new b(c)}},{14:14,15:15}],14:[function(d,f){function b(a){this.f=a}b.prototype.sb=function(a,c){if(this.a(a))c(!0);else{a=this.l(a);var e=this.j(a);c=this.o.bind(this,e,c);for(var b in a)a.hasOwnProperty(b)&&this.b(a[b],c)}};b.prototype.b=function(a,c){var e=this,b={results:[],Z:0};a.forEach(function(g,d){d=e.m.bind(e,d,a,b,c);e.f.create(g).rb(d)})};b.prototype.m=function(a,c,e,b,d){var g=this;e.results[a]=d;e.Z++;if(e.Z===c.length){var f=this.i(c);e.results.forEach(function(a,
e){f=g.c(f,a,c[e].settings.rule)});return b(f)}};b.prototype.o=function(a,c,e){a.results.push(e);a.Z++;if(a.Z===a.wb)return a=a.results.every(function(a){return a}),c(a)};b.prototype.a=function(a){return!a||0===a.length};b.prototype.i=function(a){return"EXCLUDE"===a[0].settings.rule};b.prototype.c=function(a,c,e){return"EXCLUDE"===e?a&&!c:a||c};b.prototype.l=function(a){var c={};a.forEach(function(a){c[a.type]||(c[a.type]=[]);c[a.type].push(a)});return c};b.prototype.j=function(a){return{results:[],
wb:Object.keys(a).length,Z:0}};f.g=b},{}],15:[function(d,f){function b(a,c){this.a=a;this.b=c}b.prototype.create=function(a){return new this.b[a.type+"@"+a.revision](this.a,a.settings)};f.g=b},{}],16:[function(d,f){d=d(17);f.g=d},{17:17}],17:[function(d,f){function b(){this.a=new a}var a=d(18);b.prototype.get=function(a,e,b){var c=this.a.create();c.onreadystatechange=function(){if(4===c.readyState){try{var a=JSON.parse(c.responseText)}catch(n){a={}}e(a)}};c.open("GET",a,!0);c.withCredentials=!!b;
c.send()};f.g=b},{18:18}],18:[function(d,f){function b(){}b.prototype.create=function(){return new XMLHttpRequest};f.g=b},{}],19:[function(d,f){d=d(20);f.g=d},{20:20}],20:[function(d,f){function b(a,c,e){this.f=c.adRenderingService;this.C=c.adSizeService;this.window=c.window;this.u=c.bidderParamsParser;this.s=a.containerId;this.ga=c.config.prebidUrl+"/"+this.s+"/prebid.min.js";this.J=c.consentProvider;this.a=a.settings;this.c=this.C.za(this.a);this.b=this.f.ta(this.c.width,this.c.height);this.G=this.U();
this.j="sovrn-postbid"+this.c.width+"x"+this.c.height;this.Pa=this.L();this.m=this.K();this.ea=this.u.zb(this.a.bidders,this.a.iv);this.Nb=this.a.revShareAdjustments;this.placeholder=e;this.o=this.a.cmpTimeout||1E4;this.Mb=this.a.allowAuctionWithoutConsent||!0;this.R=this.a.gdprMode||!1}b.prototype.D=function(a){this.i=void 0===a?function(){}:a;this.placeholder.appendChild(this.b);this.eb();this.bb();this.$a()};b.prototype.$a=function(){var a=this;this.fa=this.window.setInterval(function(){if(a.X()){a.window.clearInterval(a.fa);
var c=a.b.contentWindow.pbjs;a.Sa(c);a.Ya(c);a.Ma(c);a.Xa(c)}},1E3)};b.prototype.Sa=function(a){var c=this;a.que.push(function(){a.setConfig({currency:{adServerCurrency:c.a.adServerCurrency||"USD"}})})};b.prototype.Ya=function(a){var c=this;this.a.affiliateId&&a.que.push(function(){a.enableAnalytics({provider:"sovrn",options:{affiliateId:c.a.affiliateId}})})};b.prototype.Ma=function(a){var c=this;this.J.ib(function(e,b){var g="gdpr"===b||e,d="usp"===b||e;if(c.R&&(g||d))return a.que.push(function(){c.M(a,
g,d);c.B(a)});c.B(a)})};b.prototype.M=function(a,c,e){var b={};c&&(b.gdpr={cmpApi:"iab",timeout:this.o,allowAuctionWithoutConsent:!0});e&&(b.usp={cmpApi:"iab",timeout:this.o});a.setConfig({consentManagement:b})};b.prototype.Xa=function(a){var c=this;a.que.push(function(){a.setConfig({schain:{validation:"strict",config:{ver:"1.0",complete:1,nodes:[{asi:"get.s-onetag.com",sid:c.s,hp:1}]}}})})};b.prototype.B=function(a){var c=this;a.que.push(function(){c.a.revShareAdjustments&&c.u.Ua(a,c.a.revShareAdjustments);
c.H(a);c.W(a)})};b.prototype.H=function(a){a.addAdUnits([{code:this.j,bids:this.ea,mediaTypes:{banner:{sizes:this.G}}}])};b.prototype.W=function(a){a.requestBids({timeout:1E3,bidsBackHandler:this.I.bind(this,a)})};b.prototype.I=function(a){this.l=this.a.passbackHtml;var c=a.getAdserverTargetingForAdUnitCode(this.j);if(c&&c.hb_adid)return this.Oa(a,c);if(this.l)return this.Na();this.f.Ja(this.a,this.placeholder,this.i);return this.A()};b.prototype.Na=function(){var a=this.m,c=a.contentWindow.document;
if(this.a.isSafeFrame)return this.v(this.l);a.width=this.c.width;a.height=this.c.height;c.write(this.l);c.close();this.i(this.b,this.c)};b.prototype.Oa=function(a,c){var e=this.m.contentWindow.document;if(this.a.isSafeFrame)return this.v(this.V(a,c.hb_adid));a.renderAd(e,c.hb_adid);return this.i(this.b,this.T(c.hb_size))};b.prototype.T=function(a){a=a.split("x");return{width:Number(a[0]),height:Number(a[1])}};b.prototype.v=function(a){var c=this.F(this.a);c.adCode=a;this.f.Ja(c,this.placeholder,this.i);
return this.A()};b.prototype.V=function(a,c){a=a.getBidResponses()[this.j].bids.find(function(a){return a.adId===c});return a.ad?a.ad:a.adUrl?this.S(a):""};b.prototype.S=function(a){var c={frameborder:0,scrolling:"no",marginheight:0,marginwidth:0,topmargin:0,leftmargin:0,width:0,height:0,allowTransparency:!0};c.width=a.width;c.height=a.height;c.src=a.adUrl;a="<iframe";for(var e=Object.getOwnPropertyNames(c),b=0;b<e.length;b++)a+=" "+e[b]+'="'+c[e[b]]+'"';return a+"></iframe>"};b.prototype.X=function(){return this.b.contentWindow?
!!this.b.contentWindow.pbjs:!1};b.prototype.K=function(){for(var a=this.window.document.createElement("iframe"),c={frameborder:0,scrolling:"no",marginheight:0,marginwidth:0,topmargin:0,leftmargin:0,width:0,height:0,allowTransparency:!0,id:"postbid_if"},e=Object.getOwnPropertyNames(c),b=0;b<e.length;b++)a.setAttribute(e[b],c[e[b]]);return a};b.prototype.A=function(){this.b.parentNode.removeChild(this.b)};b.prototype.bb=function(){this.b.contentDocument.body.appendChild(this.m)};b.prototype.L=function(){var a=
this.window.document.createElement("script");a.setAttribute("src",this.ga);a.setAttribute("async","");a.setAttribute("type","text/javascript");return a};b.prototype.eb=function(){var a=this.f.wa(this.b);a.open();a.close();a.body.appendChild(this.Pa)};b.prototype.U=function(){var a=this.a.sizes;return a?a.map(function(a){a=a.split("x");return[Number(a[0]),Number(a[1])]}):[[this.a.width,this.a.height]]};b.prototype.F=function(a){return JSON.parse(JSON.stringify(a))};f.g=b},{}],21:[function(d,f){d=d(22);
f.g=d},{22:22}],22:[function(d,f){function b(a,c){this.ma=c;this.window=a}b.prototype.Fa=function(a){if(this.window.Qa&&"SAFEFRAME"===this.window.Qa.state)return this.window.$sf.ext.inViewPercentage()/100>=this.ma;a=a.getBoundingClientRect();return this.c(a,this.window.innerWidth)*this.b(a,this.window.innerHeight)/(a.width*a.height)>=this.ma};b.prototype.c=function(a,c){return this.a(a.right,c)-this.a(a.left,c)};b.prototype.b=function(a,c){return this.a(a.bottom,c)-this.a(a.top,c)};b.prototype.a=
function(a,c){return Math.max(0,Math.min(a,c))};f.g=b},{}],23:[function(d,f){function b(a,c,b){this.window=a;this.b=b;this.v=c;this.a={};this.f=null}b.prototype.Ja=function(a,c,b){b=void 0===b?function(){}:b;if(a.isSafeFrame)this.s(a,c,b);else{var e=this.ta(a.width,a.height);c.appendChild(e);var d=this.wa(e);d.open();d.write(this.c(a));setTimeout(function(){d.close();return b(e)},0)}};b.prototype.ta=function(a,c){var b=this.window.document.createElement("iframe");b.width=a+"px";b.height=c+"px";b.setAttribute("frameBorder",
"0");b.setAttribute("scrolling","no");b.setAttribute("marginwidth","0");b.setAttribute("marginheight","0");b.setAttribute("title","sovrn-ad");return b};b.prototype.s=function(a,c,b){var e=this;this.v.get(function(g){e.A(g,{width:a.width,height:a.height,adCode:a.adCode||e.c(a)},c,b)})};b.prototype.A=function(a,c,b,g){var e=b.id+"-safe-frame",d=this.window.document.createElement("div");d.setAttribute("id",e);b.appendChild(d);this.a[e]={placeholder:b,yb:g};this.f||this.i(a);b=new a.PosConfig({id:e,dest:e,
w:c.width,h:c.height});a.render(new a.Position(e,c.adCode,null,b));this.l(e)};b.prototype.i=function(a){this.f=new a.Config({auto:!1,renderFile:this.b.safeFrameUrls.html,onEndPosRender:this.u.bind(this)})};b.prototype.l=function(a){var c=this.a[a];c.Da=0;c.Ha=setInterval(this.m.bind(this,a,c),500)};b.prototype.m=function(a,c){if(c){if(a=this.window.document.getElementById(a))a.dispatchEvent(this.j()),a.style.display="block",a.style.visibility="inherit";c.Da++;10<c.Da&&clearInterval(c.Ha)}};b.prototype.j=
function(){if("function"===typeof this.window.Event)return new this.window.Event("load");var a=this.window.document.createEvent("CustomEvent");a.initCustomEvent("load",!1,!1,void 0);return a};b.prototype.c=function(a){return'<script src="'+this.o(a)+'">\x3c/script>'};b.prototype.u=function(a){var c=this.a[a],b=c.placeholder.querySelector("#"+a);b.setAttribute("title","sovrn-ad");clearInterval(c.Ha);c.yb(b);delete this.a[a]};b.prototype.o=function(a){var c=a.iv;a=this.b.adRenderUrl+a.zoneId+"&width="+
a.width+"&height="+a.height;c&&(a=a+"&iv="+c);return a};b.prototype.wa=function(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document};f.g=b},{}],24:[function(d,f){function b(a,c,b){this.window=a;this.a=null;this.b=c.unescape.bind(c);this.c=b}var a=d(26),c=d(25);b.prototype.gb=function(){return this.a?this.a:this.window.googletag?this.a=new a(this.window.pbjs,this.window.googletag,this.b,this.c):this.window.apntag?this.a=new c(this.window.pbjs,this.window.apntag,this.b):
null};f.g=b},{25:25,26:26}],25:[function(d,f){function b(a,c,b){this.c=a;this.a=c;this.b=b}b.prototype.qa=function(a){a=this.b(a);var c=this.f(a);this.a.modifyTag(a,{keywords:c});this.c.setTargetingForAst()};b.prototype.f=function(a){var c={};a=this.a.requests.tags[a].keywords;for(var b=Object.keys(a),g=0;g<b.length;g++)"hb_"!==b[g].substring(0,3).toLowerCase()&&(c[b[g]]=a[b[g]]);return c};b.prototype.reload=function(a){this.a.refresh(this.b(a))};f.g=b},{}],26:[function(d,f){function b(a,c,b,g){this.a=
a;this.b=c;this.s=b;this.m=g.adSizeService;this.o=g.adUnitService;this.window=g.window;this.f={};this.j={};this.H=g.config.headerBidderTargetingKeys||[];c.pubads().addEventListener("slotRenderEnded",this.A.bind(this))}b.prototype.qa=function(a){this.a.setTargetingForGPTAsync(a)};b.prototype.c=function(a){for(var c=this.b.pubads().getSlots(),b=0;b<c.length;b++)if(a===c[b].getSlotElementId())return c[b]};b.prototype.Za=function(a){var c=this,b=this.c(a);b&&b.getTargetingKeys&&b.clearTargeting&&b.getTargetingKeys().forEach(function(a){c.H.forEach(function(c){-1<
a.indexOf(c)&&b.clearTargeting(a)})})};b.prototype.reload=function(a,c,b,g){var e=this,d=this.c(this.s(a)),f=b.cb,p=b.Ta,E=b.ja;if(d&&f&&!this.j[a])return this.o.ya(d,E,p,function(f){e.j[a]=!0;e.C(d,c,f,b.Ea,g)});d&&c&&this.i(d,c);this.b.pubads().refresh([d])};b.prototype.C=function(a,c,b,g,d){var e=a.getSlotElementId(),f=this.F(a),m=this.u(a);this.b.destroySlots([a]);if(a=this.b.defineSlot(m+b,f,e))a.addService(this.b.pubads()),this.v(a,e,d),this.B(a,c,g,d),this.b.pubads().refresh([a])};b.prototype.v=
function(a,c,b){if(this.l()&&!this.I(b)){var e=this.a.getAdserverTargetingForAdUnitCode(b),d=Object.assign({},this.a.adUnits.find(function(a){return a.code===b}));d.code=c;this.a.addAdUnits(d);Object.keys(e).forEach(function(c){a.setTargeting(c,e[c])})}};b.prototype.I=function(a){return!!this.window.document.getElementById(a)};b.prototype.B=function(a,c,b,g){this.l()&&!b&&this.qa(g);c&&this.i(a,c)};b.prototype.l=function(){return this.a&&"function"===typeof this.a.setTargetingForGPTAsync};b.prototype.u=
function(a){a=a.getAdUnitPath().split("/");""===a[0]&&(a[0]="/");return a[0]+a[1]};b.prototype.F=function(a){a=this.window.document.getElementById(a.getSlotElementId());a=this.m.ca(a);return[a.width,a.height]};b.prototype.A=function(a){var c=a.slot;a=c.getSlotElementId();(a=this.f[a])&&a.forEach(function(a){c.clearTargeting(a)})};b.prototype.i=function(a,c){var b=c.reloadCount,g=c.enableVetKeyValue,d=c.dfpKeyValues,f=a.getSlotElementId();g&&this.K(a,b);d&&this.J(a,d);this.f[f]||(this.f[f]=this.G(c))};
b.prototype.K=function(a,c){c++;a.setTargeting("sovrn-signal",c)};b.prototype.J=function(a,c){Object.keys(c).forEach(function(b){a.setTargeting(b,c[b])})};b.prototype.G=function(a){var c=a.dfpKeyValues,b=[];a.enableVetKeyValue&&b.push("sovrn-signal");c&&(a=Object.keys(c),b=b.concat(a));return b};b.prototype.hb=function(a){return(a=this.c(a))?a.getAdUnitPath():""};f.g=b},{}],27:[function(d,f){function b(){}b.prototype.Ga=function(a,c){if(a.useNativeReload)return!this.b(a,c);var b=a.sizeTolerance||
10;return this.a(a).some(function(a){var e=Math.abs(c.height-a.height)<b;return Math.abs(c.width-a.width)<b&&e})};b.prototype.b=function(a,c){return-1!==(a.sizesToExclude||[]).indexOf(c.width+"x"+c.height)};b.prototype.ca=function(a){return(a=this.ba(a,"iframe")||this.ba(a,"img"))?a.getBoundingClientRect():{width:0,height:0}};b.prototype.za=function(a){return a.sizes?this.a(a).reduce(function(a,b){return a.width*a.height<b.width*b.height?b:a},{width:0,height:0}):{width:a.width,height:a.height}};b.prototype.a=
function(a){var c=a.sizes;return c?c.map(function(a){a=a.split("x");return{width:Number(a[0]),height:Number(a[1])}}):[{height:a.height,width:a.width}]};b.prototype.ba=function(a,c){a=a.getElementsByTagName(c);for(c=0;c<a.length;c++){var b=a[c].getBoundingClientRect();if(b.width&&b.height)return a[c]}};f.g=b},{}],28:[function(d,f){function b(a){this.f=a.httpClient;this.c=a.config.adUnitStatusUrl;this.a={}}b.prototype.ya=function(a,c,b,g){var e=this,d=this.i(a,c,b);a.getSlotElementId();if(this.a[d])return this.b(this.a[d],
g);this.f.get(d,function(a){e.b(a,g);e.a[d]=a})};b.prototype.i=function(a,c,b){a=a.getAdUnitPath().split("/");""===a[0]&&a.shift();return this.c+a[0]+"/"+c+"/"+a.slice(1,Number(b)+1).join("%2F")};b.prototype.b=function(a,c){"READY"===a.state&&c(a.matchingAdUnit)};f.g=b},{}],29:[function(d,f){function b(){}b.prototype.Ua=function(a,c){Object.keys(c).forEach(function(b){a.bidderSettings[b]={bidCpmAdjustment:function(a){return a*Number(c[b])}}})};b.prototype.zb=function(a,c){var b=this,g=[];Object.keys(a).forEach(function(e){g=
g.concat(b.a(e,a,c))});return g};b.prototype.a=function(a,c,b){var e=this;return c[a].map(function(c){return{bidder:a,params:e.b(a,c,b)}})};b.prototype.b=function(a,c,b){b&&"sovrn"===a&&(c.iv=b);return c};f.g=b},{}],30:[function(d,f){function b(a,c){this.window=a;this.a=c}b.prototype.ib=function(a){var c=this;this.a.xa(function(b){if(!b)return a({message:"Location not found"},null);if("US"===b)return c.a.qb(c.c.bind(c,a));c.a.pb(c.b.bind(c,a))})};b.prototype.c=function(a,c,b){if(c||b)return a(null,
"usp");a(null,null)};b.prototype.b=function(a,c,b){if(c||b)return a(null,"gdpr");a(null,null)};f.g=b},{}],31:[function(d,f){function b(){}b.prototype.escape=function(a){this.b(a)&&(a="\\3"+a.charAt(0)+" "+a.slice(1));return a.replace(/\//g,"\\/").replace(/\./g,"\\.")};b.prototype.unescape=function(a){this.a(a)&&(a=a.substr(2),a=a.charAt(0)+a.substr(2));return a.replace(/\\\//g,"/").replace(/\\\./g,".")};b.prototype.b=function(a){return isNaN(Number(parseInt(a.charAt(0))))?!1:!0};b.prototype.a=function(a){return"\\3"===
a.substr(0,2)};f.g=b},{}],32:[function(d,f){function b(a,c){this.j=a.config;this.window=a.window;this.m=a.httpClient;this.B=a.config.dfpGatewayUrl;this.i=a.adLocator;this.b=null;this.a={};this.l=c}b.prototype.o=function(a){if(this.b)return this.b;a=a.getAdUnitPath().split("/");for(var c=0;c<a.length;c++){var b=Number(a[c]);if(b)return this.b=b}return 0};b.prototype.I=function(a,c){for(var b=0;b<a.length;b++){var g=this.i.$(a[b]);if(g&&g.id===c||g&&g.querySelector("#"+c))return!0}return!1};b.prototype.c=
function(a,c,b){var e=this;b=void 0===b?0:b;if(25<=b)c({});else{var d=a.getResponseInformation();d?c(d):setTimeout(function(){e.c(a,c,++b)},200)}};b.prototype.M=function(a,c,b){this.o(a)&&this.v(c)?b(!0):b(!1)};b.prototype.v=function(a){var c=a.ordersToInclude||[],b=a.lineItemTypes||[],g=a.roadblockingType||!1;return(a.ordersToExclude||[]).length||c.length||b.length||g};b.prototype.H=function(a){a=a.lineItemTypes||[];for(var c=0;c<a.length;c++)if("AD_EXCHANGE"===a[c].type||"ADSENSE"===a[c].type)return!0;
return!1};b.prototype.F=function(a,c){var b=this,g=this.s(a);g?c(g):(this.A(a,c),1===this.a[a].length&&this.f(a,function(c){b.a[a].forEach(function(a){a(c)});b.a[a]=[];b.u(a,c)}))};b.prototype.s=function(a){try{var c=JSON.parse(this.window.localStorage.getItem("onetag-"+a));return c.expiresAt>Date.now()?c.lineItemInfo:!1}catch(e){return!1}};b.prototype.u=function(a,c){c={lineItemInfo:c,expiresAt:Date.now()+1E3*this.j.lineItemInfoTtl};try{this.window.localStorage.setItem("onetag-"+a,JSON.stringify(c))}catch(e){}};
b.prototype.f=function(a,c){var b=this;this.m.get(this.B+"/"+this.b+"/"+a,function(e){b.G(e,a,c)})};b.prototype.A=function(a,c){this.a[a]=this.a[a]||[];this.a[a].push(c)};b.prototype.G=function(a,c,b){var e=this;"PENDING"===a.state&&setTimeout(function(){e.f(c,b)},2E3);"READY"===a.state&&b(a)};b.prototype.ub=function(a,c,b){var e=this,d=this.l.escape(a.getSlotElementId());this.I(c.selectorsToExclude||[],d)?b(!0):this.M(a,c,function(d){if(!d)return b(!1);e.c(a,function(a){if(!a.lineItemId)return b(e.H(c));
e.F(a.lineItemId,function(a){return b(e.C(a,c))})})})};b.prototype.C=function(a,c){return this.K(a,c)||this.J(a,c)||this.L(a,c)};b.prototype.K=function(a,c){return c.ordersToInclude?-1===c.ordersToInclude.indexOf(a.orderId):-1<(c.ordersToExclude||[]).indexOf(a.orderId)};b.prototype.J=function(a,c){c=c.lineItemTypes||[];for(var b=0;b<c.length;b++){var d="all"===c[b].priority,f=a.priority===Number(c[b].priority);if(a.lineItemType===c[b].type&&(d||f))return!0}return!1};b.prototype.L=function(a,c){return c.roadblockingType?
"CREATIVE_SET"===a.roadblockingType:!1};f.g=b},{}],33:[function(d,f){function b(a,c,b){this.window=a.window;this.j=a.adSizeService;this.l=a.adUnitService;this.o=c;this.m=b;this.b={}}b.prototype.kb=function(a,c){for(var b=Object.keys(this.b),d=0;d<b.length;d++)this.ia(a,this.b[b[d]],c)};b.prototype.ia=function(a,c,b){var e=this.a(c);this.o.ub(c,a.settings,this.u.bind(this,e,b,a))};b.prototype.u=function(a,c,b,d){var e=this.c(a);if(!d&&this.i(e))if(b.settings.enabledAdUnitGeneration){d=this.Aa(a);e=
b.contentId;b=b.settings.adUnitLevel;if(-1!==d.getAdUnitPath().indexOf("sovrn_signal"))return c("#"+a);this.l.ya(d,e,b,function(){c("#"+a)})}else c("#"+a)};b.prototype.Ba=function(){for(var a=this.s(),c=[],b=0;b<a.length;b++){var d=a[b],f=this.c(d);this.i(f)&&c.push(d)}return c};b.prototype.nb=function(){for(var a=this.f(),c=0;c<a.length;c++){var b=a[c],d=this.a(b);this.b[d]=b}};b.prototype.Ab=function(a){var c=this.a(a);this.b[c]=a};b.prototype.s=function(){for(var a=this.f(),c=[],b=0;b<a.length;b++)c.push(this.a(a[b]));
return c};b.prototype.f=function(){return this.window.googletag.pubads().getSlots()};b.prototype.Aa=function(a){return this.b[a]||null};b.prototype.c=function(a){return(a=this.window.document.querySelector("#"+a))?this.j.ca(a):{width:0,height:0}};b.prototype.tb=function(){var a=this.window.googletag;return!!a&&a.pubadsReady};b.prototype.i=function(a){return 50<=a.width&&50<=a.height};b.prototype.Wa=function(a){var c=this;this.window.googletag.cmd.push(function(){c.window.googletag.pubads().addEventListener("slotRenderEnded",
function(c){a(c.slot)})})};b.prototype.Va=function(a){var c=this;this.window.googletag.cmd.push(function(){c.window.googletag.pubads().addEventListener("impressionViewable",function(b){b=c.a(b.slot);a("#"+b)})})};b.prototype.mb=function(){var a=this.window.googletag;a.cmd=a.cmd||[]};b.prototype.a=function(a){a=a.getSlotElementId();return this.m.escape(a)};f.g=b},{}],34:[function(d,f){function b(a,c){this.b=a;this.c=c;this.a=null}var a=d(33),c=d(32);b.prototype.get=function(b){if(!this.a){var e=new c(this.b,
this.c);this.a=new a(this.b,e,this.c)}return this.f(b)};b.prototype.f=function(a){return this.a.tb()?(this.a.mb(),this.a.nb(),a(this.a)):setTimeout(this.f.bind(this,a),1E3)};f.g=b},{32:32,33:33}],35:[function(d,f){function b(a){this.a=a.config;this.b=a.httpClient;this.window=a.window;this.j=!1;this.i=[]}b.prototype.pb=function(a){var c=this;this.xa(function(b){c.l(function(c){return b?0===c.length?a({message:"Grouping not found"},null):a(null,-1<c.indexOf(b)):a({message:"Location not found"},null)})})};
b.prototype.xa=function(a){var c=this,b=this.c("onetag-location");b?a(b):(this.i.push(a),this.j||(this.j=!0,this.b.get(this.a.geoLocationUrl,function(a){var b=a.country;b&&c.f("onetag-location",b);c.i.forEach(function(a){return a(b)});c.i=[];c.j=!1})))};b.prototype.qb=function(a){var c=this,b=this.c("onetag-us-state-location");if(b)return a(null,"CA"===b);this.b.get(this.a.geoDetectionUrl,function(b){if(!b)return a({message:"Location not found"},null);c.f("onetag-us-state-location",b.state);"CA"===
b.state?a(null,!0):a(null,!1)})};b.prototype.f=function(a,b){b={value:b,expiresAt:Date.now()+1E3*this.a.geoLocationCacheTtl};try{this.window.localStorage.setItem(a,JSON.stringify(b))}catch(e){}};b.prototype.c=function(a){try{var b=JSON.parse(this.window.localStorage.getItem(a));return b.expiresAt>Date.now()?b.value:!1}catch(e){return!1}};b.prototype.l=function(a){var b=this,e=this.c("onetag-grouping_EU");e?a(e):this.b.get(this.a.geoGroupingUrl+"regionalbloc/EU",function(c){var e=[];c.countries&&(e=
c.countries.map(function(a){return a.code}),b.f("onetag-grouping_EU",e));return a(e)})};f.g=b},{}],36:[function(d,f){function b(a,b,e,d){this.o=a;this.window=a.window;this.C=a.adLocator;this.s=a.engagementBeacon;this.F=a.config;this.a=e;this.L=b;this.i=d;this.c={};this.A={};this.m=null;this.l={};this.b={}}b.prototype.D=function(a,b){var c=this;this.m=a.containerId;this.l=a.settings||{};this.A=b;this.S(a.contents,b);this.R(a.contents)&&(this.a.D(this.b),this.ga(a.contents)&&this.i.get(function(a){a.Va(c.fa.bind(c))}));
this.W()&&this.T()};b.prototype.jb=function(a,b){var c=this,d={},f={},h=this.f(a),n=this.f(a);h.contents=[];n.contents=[];Object.keys(b).forEach(function(e){var g=b[e],m=g.config;g=g.contentFunction;var p=e.split("@")[0],q=c.M(p,a);c.b[p]=m;m.executeImmediately?(d[e]=g,h.contents.push.apply(h.contents,q instanceof Array?q:V(U(q)))):(f[e]=g,n.contents.push.apply(n.contents,q instanceof Array?q:V(U(q))))});return{onStart:{containerDto:h,contentFunctions:d},onPageLoad:{containerDto:n,contentFunctions:f}}};
b.prototype.M=function(a,b){var c=this,d=this.B((b.user||{}).settings,b.settings);return b.contents.reduce(function(b,e){a===e.type&&(e.settings=c.B(d,e.settings),b.push(e));return b},[])};b.prototype.B=function(a,b){a=a||{};var c=this.f(a),d=b||{};Object.keys(d).forEach(function(a){c[a]=d[a]});return c};b.prototype.S=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];this.J(a[c],this.K.bind(this,d,b[d.type+"@"+d.revision]))}};b.prototype.K=function(a,b,e){e&&this.X(a,b)};b.prototype.J=function(a,
b){this.L.sb(a.filters,function(a){return b(a)})};b.prototype.X=function(a,b){this.v(a)?this.U(b,a):this.C.D(b,a,this.o,this.b[a.type])};b.prototype.T=function(){var a=this;this.H||(this.V(function(b){a.s.vb({isLightMode:!!a.l.isVetLicensing,containerId:a.m,doNotTrack:b,percentInView:a.o.viewability.ma},function(){a.u()})}),this.H=!0)};b.prototype.u=function(){var a=this;return this.i.get(function(b){b=b.Ba();0===b.length&&setTimeout(a.u.bind(a),1E3);for(var c=0;c<b.length;c++)a.s.pa("#"+b[c],b[c])})};
b.prototype.U=function(a,b){var c=this,d=b.settings,f=b.contentId;this.a.Hb(this.b);d.dfpMode?this.i.get(function(d){var e=d.Ba().map(function(a){return"#"+a});c.j(a,b,e);d.kb(b,function(a){c.a.da([a],f)});d.Wa(c.G.bind(c,a,b,d))}):(d=this.I(d.selectors||d.selector),this.a.da(d,f),this.j(a,b,d))};b.prototype.G=function(a,b,d,g){var c=this,e=b.contentId;d.Ab(g);d.ia(b,g,function(d){c.j(a,b,[d]);c.a.da([d],e)})};b.prototype.I=function(a){return[].concat(a)};b.prototype.j=function(a,b,d){if(b.settings.useImpressionViewable)this.ea(d,
b);else for(var c=0;c<d.length;c++){var e=d[c],f=this.f(b);f.settings.selector=e;delete f.settings.selectors;this.a.Ia(f,a)}};b.prototype.ea=function(a,b){var c=this;a.forEach(function(a){c.c[a]||(c.c[a]=[]);c.c[a].push(b)})};b.prototype.ga=function(a){for(var b=0;b<a.length;b++)if(a[b].settings.useImpressionViewable)return!0;return!1};b.prototype.fa=function(a){if(this.c[a])for(var b=0;b<this.c[a].length;b++){var d=this.f(this.c[a][b]),f=this.A[d.type+"@"+d.revision];d.settings.selector=a;delete d.settings.selectors;
this.a.Ia(d,f)}};b.prototype.f=function(a){return JSON.parse(JSON.stringify(a))};b.prototype.R=function(a){for(var b=0;b<a.length;b++)if(this.v(a[b]))return!0;return!1};b.prototype.v=function(a){return-1!==a.type.indexOf("onetag-vet")};b.prototype.W=function(){var a=this.F.featureToggles.engagementBeacon;return this.l.disableEngagementTracking||!a?!1:!0};b.prototype.V=function(a){var b=this.window.navigator.ab||this.window.ab;"1"===b||"yes"===b?a(!0):a(!1)};f.g=b},{}],37:[function(d,f){function b(a){this.a=
a}b.prototype.create=function(a,b,d){return new this.a(a,b,d)};f.g=b},{}],38:[function(d,f){function b(a,b){this.window=a;this.a=!1;this.b=b}b.prototype.get=function(a){var b=this;this.f();this.c()?a(this.window.$sf.host):setTimeout(function(){b.get(a)},500)};b.prototype.f=function(){if(!this.window.$sf&&!this.a){this.a=!0;var a=this.window.document.createElement("script");a.setAttribute("src",this.b.safeFrameUrls.lib);this.window.document.body.appendChild(a)}};b.prototype.c=function(){var a=this.window.$sf;
return a&&a.host&&a.host.boot?!0:!1};f.g=b},{}],39:[function(d,f){function b(a){this.window=a}b.prototype.create=function(a){return new this.window.MutationObserver(a)};f.g=b},{}],40:[function(d,f){function b(a,b){this.window=a;this.b=b;this.a=null}b.prototype.i=function(){var a=this.window.pbjs;return a&&"function"===typeof a.requestBids?a:null};b.prototype.aa=function(a,b,d){var c=this.i();if(this.a=this.b.gb())this.a.Za(a),c&&!d.Ea?this.j(a,b,c,d):this.a.reload(a,b,d)};b.prototype.j=function(a,
b,d,f){var c=this,e=this.f(a,d);e?d.requestBids({adUnits:[e],bidsBackHandler:function(){c.a.qa(e.code);c.a.reload(a,b,f,e.code)}}):this.a.reload(a,b,f)};b.prototype.f=function(a,b){b=b.adUnits;if(!b)return null;for(var c=this.a.hb(a),d=b.length-1;0<=d;--d)if(b[d].code===a||c===b[d].code)return this.c(b[d]);return null};b.prototype.c=function(a){for(var b=a.bids,d=0;d<b.length;d++)"sovrn"===b[d].bidder&&(b[d].params.iv="vet");return a};f.g=b},{}],41:[function(d,f){function b(a,b,d,f){this.A=a;this.l=
a.viewableEngagedTime;this.B=a.engagementBeacon;this.f=a.adLocator;this.i=a.adSizeService;this.window=a.window;this.L=b;this.H=a.config.lazyLoadWaitTime||20;this.K=d;this.v=f;this.c={};this.a={}}b.prototype.D=function(){this.l.start()};b.prototype.Hb=function(a){this.b=a};b.prototype.da=function(a,b){for(var c=0;c<a.length;c++){var d=a[c]+"-"+b;this.c[d]||(this.c[d]=!0)}};b.prototype.Ia=function(a,b){this.J(a,b);this.u(a,b)};b.prototype.u=function(a,b){var c=this,d={childList:!0,subtree:!0},f=a.settings.selector,
h=this.f.$(f),n=f+"-"+a.contentId;h?(this.j(a,b,h),this.a[n]||this.K.create(function(d,e){d.forEach(function(){c.j(a,b,h);c.a[n]&&e.disconnect()})}).observe(h,d)):setTimeout(this.u.bind(this,a,b),1E3)};b.prototype.J=function(a,b){var c=a.settings.selector,d=this.f.$(c),f=c+"-"+a.contentId;d&&this.j(a,b,d);this.a[f]||this.X(a,b,c)};b.prototype.X=function(a,b,d){var c=this,e=d+"-"+a.contentId,f=0,n=setInterval(function(){var g=c.f.$(d);f++;g&&(c.j(a,b,g),(c.a[e]||f>c.H)&&clearInterval(n))},1E3)};b.prototype.j=
function(a,b,d){var c=this.i.ca(d);this.V(a,c)&&this.C(a,b,d)};b.prototype.V=function(a,b){var c=a.settings;return this.a[c.selector+"-"+a.contentId]?!1:this.i.Ga(c,b)};b.prototype.C=function(a,b,d){this.a[(a.settings||{}).selector+"-"+a.contentId]={fb:b,definition:a,element:d};this.l.Lb(a,d,this.R.bind(this))};b.prototype.R=function(a){var b=a.Gb,d=b+"-"+a.ja,f=this.a[d];if(!this.c[d])return this.U(f)?(this.m(d),!1):!0;f=f.definition.settings;var m=this.i.ca(a.element);if(!this.i.Ga(f,m))return this.m(d),
!1;this.T(d);f.useNativeReload||this.l.Db(a);this.aa(b,a.la,d);return!0};b.prototype.U=function(a){return this.s(a)?!0:!this.G()};b.prototype.s=function(a){return"onetag-vet-header-content"===a.definition.type};b.prototype.G=function(){for(var a=Object.keys(this.a),b=0;b<a.length;b++)if(this.s(this.a[a[b]]))return!0;return!1};b.prototype.m=function(a){delete this.a[a];this.l.Eb(a)};b.prototype.T=function(a){a=this.a[a].element;var b=a.getBoundingClientRect(),d=b.width;a.style.minHeight=b.height+"px";
a.style.minWidth=d+"px";a.style.boxSizing="border-box"};b.prototype.aa=function(a,b,d){var c=this.a[d].definition,e=c.contentId;c.settings.useNativeReload?this.M(c,a,b):(this.I(this.a[d]),this.W(a,d,e));this.B.pa(a,e)};b.prototype.W=function(a,b,d){var c=this,e=Object.keys(this.a);1>=e.length||e.forEach(function(e){c.o(e,d)===a&&e!==b&&c.m(e)})};b.prototype.M=function(a,b,d){var c=a.settings;this.L.aa(b.substring(1),{enableVetKeyValue:c.enableVetKeyValue,dfpKeyValues:c.dfpKeyValues,reloadCount:d},
{cb:c.enabledAdUnitGeneration,ja:a.contentId,Ea:"gpt"===c.headerBiddingType,Ta:c.adUnitLevel});this.S(c.selector,a.contentId)};b.prototype.o=function(a,b){return a.substring(0,a.length-b.length-1)};b.prototype.S=function(a,b){var c=this;Object.keys(this.c).forEach(function(d){a===c.o(d,b)&&(delete c.c[d],c.F(a,d))})};b.prototype.F=function(a,b){var c=this;this.v.get(function(d){var e=c.a[b];if(e){var f=e.definition.contentId;d.ia(e.definition,d.Aa(a.substring(1)),function(a){c.da([a],f)})}})};b.prototype.I=
function(a){this.f.D(a.fb,a.definition,this.A,this.b[a.definition.type])};f.g=b},{}],42:[function(d,f){function b(a,b){this.m=a.viewability;this.c=a.engagementMonitor;this.f=a.adSizeService;this.window=a.window;this.a={};this.b=null;this.i=!1;this.u=b||20}b.prototype.start=function(){var a=this;this.i||(this.c.start(),this.b=this.l(),this.v(),this.c.sa("user_active",function(){a.b||(a.b=a.l())}),this.c.sa("user_inactive",function(){a.window.clearInterval(a.b);a.b=null}),this.i=!0)};b.prototype.Lb=
function(a,b,d){var c=a.settings;a=a.contentId;var e=c.selector;this.a[e+"-"+a]={ra:0,na:0,Cb:c.reloadTime||20,Gb:e,ja:a,element:b,la:0,Bb:c.reloadLimit||Infinity,size:{width:c.width,height:c.height},xb:d}};b.prototype.Eb=function(a){delete this.a[a]};b.prototype.v=function(){this.window.setInterval(this.j.bind(this,this.B),1E3)};b.prototype.l=function(){return this.window.setInterval(this.j.bind(this,this.C),1E3)};b.prototype.j=function(a){for(var b in this.a)this.a.hasOwnProperty(b)&&a.call(this,
this.a[b])};b.prototype.B=function(a){a.na++};b.prototype.C=function(a){var b=this.o(a);this.m.Fa(b)&&a.ra++;this.A(b,a)&&this.aa(a)};b.prototype.o=function(a){if(!a.Y||!this.s(a)){var b=this.f.ba(a.element,"iframe");a.Y=b||this.f.ba(a.element,"img")}return a.Y?a.Y:a.element};b.prototype.s=function(a){for(var b=a.Y;b.parentNode;)if(b=b.parentNode,b===a.element)return!0;return!1};b.prototype.aa=function(a){a.xb(a)&&(a.la++,a.ra=0,a.na=0,a.Y=null)};b.prototype.A=function(a,b){a=this.m.Fa(a);var c=b.ra>=
b.Cb,d=b.na>=this.u;b=b.la>=b.Bb;return a&&c&&!b&&d};b.prototype.Db=function(a){for(var b=a.element.childNodes,d=b.length;0<d;d--)a.element.removeChild(b[d-1])};f.g=b},{}],43:[function(d,f){function b(a){this.window=a}b.prototype.lb=function(){try{var a=this.a(this.window.top);a.__onetag.state="FRIENDLY"}catch(c){a=this.a(this.window),a.__onetag.state="UNFRIENDLY",a.$sf&&a.$sf.ext&&(a.__onetag.state="SAFEFRAME")}return a};b.prototype.a=function(a){a.__onetag||(a.__onetag={});return a};f.g=b},{}],
44:[function(d,f){function b(d,f,G,r){var F=new g(b.window),w=d.containerId,H=d.settings.isVetLicensing,u=d.settings.disengagementThreshold,I=d.settings.minimumAdLoadtime,k=F.lb();k.__onetag||(k.__onetag={});k.__onetag.containerIds=k.__onetag.containerIds||{};if(k.__onetag.containerIds[w])return!1;k.__onetag.containerIds[w]=!0;var l=new ba,J=new n,y=new ca;w=new da;F=new ea(k);var K=new m(k,r);K=new h(k,K,r);var aa=new fa(k);H=new ha(k,c(H));u=new ia(k,u);var la=new ja(ka),na=new ma(k,r);l={config:r,
window:k,adLocator:aa,httpClient:l,viewability:H,engagementMonitor:u,adRenderingService:K,adSizeService:J,postbidFactory:la,bidderParamsParser:y,engagementBeacon:na};y=new E(k,w,l);J=new Y(k,y);u=new oa(l);l.adServerHandlerProvider=y;l.geoLocationService=u;l.viewableEngagedTime=new pa(l,I);l.adUnitService=new p(l);l.consentProvider=new qa(k,u,r);r=new q(l,w);G=new ra(l,G);I=new Z(l,J,F,r);var z=new e(l,G,I,r),S=!1,v=z.jb(d,f);z.D(v.onStart.containerDto,v.onStart.contentFunctions);if(a(k.document))return z.D(v.onPageLoad.containerDto,
v.onPageLoad.contentFunctions),!0;k.document.addEventListener("readystatechange",function(){!S&&a(k.document)&&(z.D(v.onPageLoad.containerDto,v.onPageLoad.contentFunctions),S=!0)});return!0}function a(a){a=a.readyState;return"interactive"===a||"complete"===a}function c(a){var b=.5;a&&(b=1);return b}var e=d(36),g=d(43),m=d(38),h=d(23),n=d(27),p=d(28),E=d(24),Y=d(40),Z=d(41),q=d(34),ea=d(39),fa=d(5),ba=d(16),ia=d(7),ha=d(21),ra=d(13),oa=d(35),ka=d(19),ja=d(37),pa=d(42),ca=d(29),da=d(31),qa=d(30),ma=
d(3);b.window=window;f.g=b},{13:13,16:16,19:19,21:21,23:23,24:24,27:27,28:28,29:29,3:3,30:30,31:31,34:34,35:35,36:36,37:37,38:38,39:39,40:40,41:41,42:42,43:43,5:5,7:7}],45:[function(d){var f={"onetag-vet-postbid-content@*":d(2)},b={"onetag-screensize-filter@*":d(1)};d(44)({containerId:"174b89ff-9d3f-47e5-aae2-826c0bcf3f7b",contents:[{name:"VET 300x600",containerId:"174b89ff-9d3f-47e5-aae2-826c0bcf3f7b",contentId:"5e68418e-fab7-4a8b-bac5-44b0667ab6b4",type:"onetag-vet-postbid-content",revision:"*",
repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["300x600"],passbackHtml:'\x3c!-- RON 300x600 --\x3e\n<div id="onscroll-ad-ron-300-x-600"></div>\n\n\x3c!-- OnScroll tag: RON 300x600 --\x3e\n<script src="//tags.onscroll.com/19ccc172-5e3d-4da0-a3d4-27d79b6890be/tag.min.js" async defer>\x3c/script>',bidders:{appnexus:[{label:"Appnexus 1019",placementId:"12336968"}],openx:[{label:"Openx 1",unit:"539445719",delDomain:"onscroll-d.openx.net"}],
rubicon:[{label:"Rubicon",accountId:"15380",siteId:"102602",zoneId:"764458",sizes:["10"]}]},dfpMode:!0,reloadTime:"30",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],roadblockingType:!1,currencyModule:!0,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"}]},filters:[],enabled:!0},{name:"VET 728x90",containerId:"174b89ff-9d3f-47e5-aae2-826c0bcf3f7b",contentId:"7c325ed3-b182-4fab-a06a-b239fe608911",type:"onetag-vet-postbid-content",
revision:"*",repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["728x90"],passbackHtml:'\x3c!-- RON 728x90 --\x3e\n<div id="onscroll-ad-ron-728-x-90"></div>\n\n\x3c!-- OnScroll tag: RON 728x90 --\x3e\n<script src="//tags.onscroll.com/6cb58e35-c0fb-413a-a831-8f434344d343/tag.min.js" async defer>\x3c/script>',bidders:{appnexus:[{label:"Appnexus 1019",placementId:"12336961"}],openx:[{label:"Openx 1",unit:"539445722",delDomain:"onscroll-d.openx.net"}],
rubicon:[{label:"Rubicon",accountId:"15380",siteId:"102602",zoneId:"764462",sizes:["2"]}]},dfpMode:!0,reloadTime:"30",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],roadblockingType:!1,currencyModule:!0,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"}]},filters:[],enabled:!0},{name:"VET 300x250",containerId:"174b89ff-9d3f-47e5-aae2-826c0bcf3f7b",contentId:"9f921608-7b18-457d-89aa-cca439252895",type:"onetag-vet-postbid-content",
revision:"*",repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["300x250"],passbackHtml:'\x3c!-- RON 300x250 --\x3e\n<div id="onscroll-ad-ron-300-x-250"></div>\n\n\x3c!-- OnScroll tag: RON 300x250 --\x3e\n<script src="//tags.onscroll.com/94d98371-69b6-450a-b981-a564a2ff5653/tag.min.js" async defer>\x3c/script>',bidders:{appnexus:[{label:"Appnexus 1019",placementId:"12336962"}],openx:[{label:"Openx 1",unit:"539445702",delDomain:"onscroll-d.openx.net"}],
rubicon:[{label:"Rubicon",accountId:"15380",siteId:"102602",zoneId:"764456",sizes:["15"]}]},dfpMode:!0,reloadTime:"30",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],roadblockingType:!1,currencyModule:!0,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"}]},filters:[],enabled:!0},{name:"VET 970x250",containerId:"174b89ff-9d3f-47e5-aae2-826c0bcf3f7b",contentId:"44f794f1-02f5-4d5d-b95a-db39658c8ce4",type:"onetag-vet-postbid-content",
revision:"*",repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["970x250"],passbackHtml:'\x3c!-- RON 970x250 --\x3e\n<div id="onscroll-ad-ron-970-x-250"></div>\n\n\x3c!-- OnScroll tag: RON  970x250 --\x3e\n<script src="//tags.onscroll.com/4dbcc0ed-8ee2-4f5f-ae33-c26cb1085267/tag.min.js" async defer>\x3c/script>',bidders:{appnexus:[{label:"Appnexus 1019",placementId:"12336963"}],openx:[{label:"Openx 1",unit:"539445724",delDomain:"onscroll-d.openx.net"}],
rubicon:[{label:"Rubicon",accountId:"15380",siteId:"102602",zoneId:"764464",sizes:["57"]}]},dfpMode:!0,reloadTime:"30",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],roadblockingType:!1,currencyModule:!0,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"}]},filters:[],enabled:!0},{name:"VET 320x50",containerId:"174b89ff-9d3f-47e5-aae2-826c0bcf3f7b",contentId:"6373dc0c-c67e-4613-b232-80bfbe466613",type:"onetag-vet-postbid-content",
revision:"*",repo:"@onscroll",settings:{integrationType:"vet-reload",demandType:"services",headerBiddingType:"postbid",sizes:["320x50"],passbackHtml:'\x3c!-- RON 320x50 --\x3e\n<div id="onscroll-ad-ron-320-x-50"></div>\n\n\x3c!-- OnScroll tag: RON 320x50 --\x3e\n<script src="//tags.onscroll.com/41e3e044-e7ce-4c09-b104-9edb01d4d14f/tag.min.js" async defer>\x3c/script>',bidders:{appnexus:[{label:"Appnexus 1019",placementId:"12336978"}],rubicon:[{label:"Rubicon",accountId:"15380",siteId:"102602",zoneId:"764460",
sizes:["43"]}],openx:[{label:"OpenX",unit:"540935051",delDomain:"onscroll-d.openx.net"}]},dfpMode:!0,reloadTime:"30",customDeviceTypes:[{name:"Phone",min:"1",max:"768"},{name:"Tablet",min:"769",max:"992"},{name:"Desktop",min:"993",max:"9999"}],isSafeFrame:!0,roadblockingType:!1,currencyModule:!0,sizeTolerance:81,lineItemTypes:[{type:"SPONSORSHIP",priority:"all"}]},filters:[{type:"onetag-screensize-filter",repo:"@onscroll",revision:"*",settings:{min:"769",max:"992",rule:"EXCLUDE"}},{type:"onetag-screensize-filter",
repo:"@onscroll",revision:"*",settings:{min:"993",max:"9999",rule:"EXCLUDE"}}],enabled:!0}],settings:{revShareAdjustments:{appnexus:1,rubicon:1,openx:1}},user:{settings:{}}},f,b,{prebidUrl:"https://prebid.s-onetag.com",adRenderUrl:"//ap.lijit.com/www/delivery/fpi.js?z=",cookieEndpoint:"https://ap.lijit.com/readerinfo/v2",dfpGatewayUrl:"https://dfp-gateway.s-onetag.com/1",featureToggles:{engagementBeacon:!0},safeFrameUrls:{html:"//get.s-onetag.com/safeframe-urls/1.0.0/safe-frame-internal.html",lib:"//get.s-onetag.com/safeframe-urls/1.0.0/safe-frame.js"},
safeFrameTarget:"#sf_pos_rel_el_",geoLocationUrl:"//onetag-geo.s-onetag.com/",geoGroupingUrl:"//onetag-geo-grouping.s-onetag.com/",geoLocationCacheTtl:86400,lineItemInfoTtl:86400,noTrackingGeoGroup:"EU",cmpUrl:"//sovrn.mgr.consensu.org",sovrnVendorId:13,portalUrl:"https://get.s-onetag.com/onetag-sync-portal/Portal.html",beaconUrl:"https://beacon.s-onetag.com/beacon.min.js",dataBeaconsUrl:"https://data-beacons.s-onetag.com/dataBeacons.min.js",adUnitStatusUrl:"https://gam-ad-unit-inspector.s-onetag.com/",
headerBidderTargetingKeys:["hb_","ix_","amznp","amznbid"]})},{1:1,2:2,44:44}]},{},[45]);})()
/* 
date-of-deployment: UTC2020-02-07T16:45:31Z 
contents:
onetag-vet-postbid-content: 3.1.1911040915
filters:
onetag-screensize-filter: 1.0.1911051046
*/