(function(g){var window=this;var bqa=function(a,b){return g.Tb(a,b)},U5=function(a,b,c){a.w.set(b,c)},V5=function(a){U5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.A)()).toString(36));
return a},W5=function(a,b,c){g.Ha(c)||(c=[String(c)]);
g.Qm(a.w,b,c)},cqa=function(a,b){var c=[];
g.Wi(b,function(d){try{var e=g.Cn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Bn(e)&&c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.y)(c,function(d){g.Cn.prototype.remove.call(this,d)},a)},X5=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},eqa=function(a,b){g.Xa(a,b)||a.push(b)},Y5=function(a){var b=0,c;
for(c in a)b++;return b},Z5=function(a,b){var c=b instanceof g.yc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},$5=function(){},fqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a){if(a.nd&&"function"==typeof a.nd)return a.nd();
if("string"===typeof a)return a.split("");if(g.Ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ob(a)},hqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ia(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Xd&&"function"==typeof a.Xd)var c=a.Xd();else if(a.nd&&"function"==typeof a.nd)c=void 0;else if(g.Ia(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Pb(a);d=gqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},iqa=function(a,b,c,d){var e=new g.Em(null,void 0);
a&&g.Fm(e,a);b&&g.Gm(e,b);c&&g.Hm(e,c);d&&(e.u=d);return e},a6=function(a,b){g.Ao[a]=!0;
var c=g.yo();c&&c.publish.apply(c,arguments);g.Ao[a]=!1},b6=function(a){try{var b=(0,g.hy)(),c=(0,g.gy)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},jqa=function(){var a=(0,g.gy)();
a&&dqa(a,a.o.hf(!0))},c6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Bm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",kqa(this,a.capabilities||""),lqa(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},kqa=function(a,b){a.capabilities.clear();
(0,g.Td)(b.split(","),g.Na(bqa,mqa)).forEach(function(c){a.capabilities.add(c)})},lqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},d6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},e6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},f6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nqa=function(a){return new d6(a)},g6=function(a){return g.Ha(a)?(0,g.ee)(a,nqa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return g.Ha(a)?"["+(0,g.ee)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},oqa=function(a){return(0,g.ee)(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.Ua(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.Ua(a,function(c){return e6(c,b)})},m6=function(){var a=g.jy("yt-remote-connected-devices")||[];
g.nb(a);return a},pqa=function(a){if(g.Ya(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ee)(a,function(d,e){return 0==e?d:d.substring(c.length)})},n6=function(a){g.iy("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.jy("yt-remote-device-id");a||(a=j6(),g.iy("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Xa(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=m6(),b=p6();
g.Xa(a,b);g.GL()&&g.pb(a,b);a=pqa(a);if(g.Ya(a))try{g.qr("remote_sid")}catch(c){}else try{g.pr("remote_sid",a.join(","),-1)}catch(c){}},r6=function(){return g.jy("yt-remote-session-browser-channel")},qqa=function(){return g.jy("yt-remote-local-screens")||[]},rqa=function(){g.iy("yt-remote-lounge-token-expiration",!0,86400)},sqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ee)(qqa(),function(d){return d.loungeToken}),c=(0,g.ee)(a,function(d){return d.loungeToken});
(0,g.$g)(c,function(d){return!g.Xa(b,d)})&&rqa();
g.iy("yt-remote-local-screens",a,31536E3)},tqa=function(a,b){g.iy("yt-remote-session-browser-channel",a);
g.iy("yt-remote-session-screen-id",b);var c=m6(),d=p6();g.Xa(c,d)||c.push(d);n6(c);q6()},s6=function(a){a||(b6("yt-remote-session-screen-id"),b6("yt-remote-session-video-id"));
q6();a=m6();g.ab(a,p6());n6(a)},uqa=function(){if(!t6){var a=g.Mn();
a&&(t6=new g.wn(a))}return t6?!!t6.get("yt-remote-use-staging-server"):!1},vqa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},wqa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?xqa(a.shift(),function(){u6(a)}):v6()},yqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},xqa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=wqa();
a&&a(!1,"No cast extension found")},Aqa=function(){if(zqa){var a=2,b=wqa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;xqa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},Bqa=function(){Aqa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},w6=function(a,b,c){g.E.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Sc=b;this.B=(0,g.x)(this.yC,this);this.o=!1;this.u=0;this.w=this.Fa=null;this.A=[]},x6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return fqa(a)},y6=function(){},z6=function(){},Cqa=function(){},Eqa=function(a){return(a=Dqa(a))?new ActiveXObject(a):new XMLHttpRequest},Dqa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.D=d||1;this.B=45E3;this.A=new g.c_(this);this.u=new g.bl;this.u.setInterval(250)},Gqa=function(a,b,c){a.fi=1;
a.Vf=V5(b.clone());a.uh=c;a.C=!0;Fqa(a,null)},B6=function(a,b,c,d,e){a.fi=1;
a.Vf=V5(b.clone());a.uh=null;a.C=c;e&&(a.fz=!1);Fqa(a,d)},Fqa=function(a,b){a.Ki=(0,g.A)();
C6(a);a.Bg=a.Vf.clone();W5(a.Bg,"t",a.D);a.Tk=0;a.uc=a.o.Uo(a.o.Ik()?b:null);0<a.Ap&&(a.An=new g.el((0,g.x)(a.fA,a,a.uc),a.Ap));a.A.ga(a.uc,"readystatechange",a.AL);var c=a.Yg?g.Zb(a.Yg):{};a.uh?(a.co="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.uc.send(a.Bg,a.co,a.uh,c)):(a.co="GET",a.fz&&!g.Id&&(c.Connection="close"),a.uc.send(a.Bg,a.co,null,c));a.o.ne(1)},Jqa=function(a,b,c){for(var d=!0;!a.Lg&&a.Tk<c.length;){var e=Hqa(a,c);
if(e==D6){4==b&&(a.lg=4,E6(15),d=!1);break}else if(e==Iqa){a.lg=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.lg=1,E6(17),d=!1);a.oe=a.oe&&d;d||(G6(a),H6(a))},Hqa=function(a,b){var c=a.Tk,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Iqa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Tk=d+c;return e},Lqa=function(a,b){a.Ki=(0,g.A)();
C6(a);var c=b?window.location.hostname:"";a.Bg=a.Vf.clone();U5(a.Bg,"DOMAIN",c);U5(a.Bg,"t",a.D);try{a.ue=new ActiveXObject("htmlfile")}catch(n){G6(a);a.lg=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in Kqa)k=I6[l]=Kqa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Qc(g.pc("b/12014412"),d+"</body></html>");a.ue.open();a.ue.write(g.Lc(c));a.ue.close();a.ue.parentWindow.m=(0,g.x)(a.PK,a);a.ue.parentWindow.d=(0,g.x)(a.ny,a,!0);a.ue.parentWindow.rpcClose=(0,g.x)(a.ny,a,!1);c=a.ue.createElement("DIV");a.ue.parentWindow.document.body.appendChild(c);d=g.Bc(a.Bg.toString());d=g.Xc(g.zc(d));d=g.Qc(g.pc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Rc(c,d);a.o.ne(1)},C6=function(a){a.As=(0,g.A)()+a.B;
Mqa(a,a.B)},Mqa=function(a,b){if(null!=a.Zi)throw Error("WatchDog timer not null");
a.Zi=J6((0,g.x)(a.XK,a),b)},K6=function(a){a.Zi&&(g.u.clearTimeout(a.Zi),a.Zi=null)},H6=function(a){a.o.hv()||a.Lg||a.o.sn(a)},G6=function(a){K6(a);
g.xi(a.An);a.An=null;a.u.stop();g.e_(a.A);if(a.uc){var b=a.uc;a.uc=null;b.abort();b.dispose()}a.ue&&(a.ue=null)},F6=function(a,b){try{a.o.hy(a,b),a.o.ne(4)}catch(c){}},Oqa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Nqa(a,b,function(k){k?c(!0):g.u.setTimeout(function(){Oqa(a,b,c,d,f)},f)})}},Nqa=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Z5(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Pqa=function(a){this.o=a;
this.u=new y6},Qqa=function(a){var b=M6(a.o,a.hj,"/mail/images/cleardot.gif");
V5(b);Oqa(b.toString(),5E3,(0,g.x)(a.wB,a),3,2E3);a.ne(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.yd=new A6(a,void 0,void 0,void 0),a.yd.Yg=a.yp,b=a.o,b=M6(b,b.Ik()?a.Fj:null,a.zp),E6(5),!g.Gd||g.kd(10))W5(b,"TYPE","xmlhttp"),B6(a.yd,b,!1,a.Fj,!1);else{W5(b,"TYPE","html");var c=a.yd;a=!!a.Fj;c.fi=3;c.Vf=V5(b.clone());Lqa(c,a)}},P6=function(a){g.rk.call(this);
this.headers=new g.Bm;this.P=a||null;this.w=!1;this.U=this.o=null;this.Z=this.H="";this.C=0;this.A="";this.B=this.da=this.G=this.T=!1;this.D=0;this.J=null;this.aa="";this.K=this.V=!1},Rqa=function(a){return g.Gd&&g.jd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Sqa=function(a){return"content-type"==a.toLowerCase()},Uqa=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;Tqa(a);Q6(a)},Tqa=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Wqa=function(a){if(a.w&&"undefined"!=typeof g.k_)if(a.U[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.cl(a.kv,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vf(1,String(a.H));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!Vqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";Tqa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Xqa(a);
var c=a.o,d=a.U[0]?g.Ea:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Xqa=function(a){a.o&&a.K&&(a.o.ontimeout=null);
a.J&&(g.u.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.Z+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Yqa=function(a,b){this.o=a;
this.map=b;this.context=null},Zqa=function(a){g.Tj.call(this,"statevent",a)},$qa=function(a,b){g.Tj.call(this,"timingevent",a);
this.size=b},ara=function(a){g.Tj.call(this,"serverreachability",a)},dra=function(a){bra(a);
if(3==a.o){var b=a.mk++,c=a.Wl.clone();U5(c,"SID",a.w);U5(c,"RID",b);U5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.fi=2;b.Vf=V5(c.clone());Z5(new Image,b.Vf.toString());b.Ki=(0,g.A)();C6(b)}cra(a)},era=function(a){a.RB(1,0);
a.Wl=M6(a,null,a.xp);W6(a)},bra=function(a){a.Zf&&(a.Zf.abort(),a.Zf=null);
a.Qb&&(a.Qb.cancel(),a.Qb=null);a.jf&&(g.u.clearTimeout(a.jf),a.jf=null);X6(a);a.sd&&(a.sd.cancel(),a.sd=null);a.gg&&(g.u.clearTimeout(a.gg),a.gg=null)},fra=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Yqa(a.eH++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.sd||a.gg||(a.gg=J6((0,g.x)(a.my,a),0),a.Th=0)},hra=function(a,b){if(1==a.o){if(!b){a.mk=Math.floor(1E5*Math.random());
var c=a.mk++,d=new A6(a,"",c,void 0);d.Yg=null;var e=Y6(a),f=a.Wl.clone();U5(f,"RID",c);U5(f,"CVER","1");V6(a,f);Gqa(d,f,e);a.sd=d;a.o=2}}else 3==a.o&&(b?gra(a,b):0==a.u.length||a.sd||gra(a))},gra=function(a,b){if(b)if(6<a.Mg){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.mk-1;var d=Y6(a)}else c=b.G,d=b.uh;else c=a.mk++,d=Y6(a);var e=a.Wl.clone();U5(e,"SID",a.w);U5(e,"RID",c);U5(e,"AID",a.si);V6(a,e);c=new A6(a,a.w,c,a.Th+1);c.Yg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.sd=c;Gqa(c,e,d)},V6=function(a,b){if(a.Pc){var c=a.Pc.Ju();
c&&g.Ib(c,function(d,e){U5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Mg&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Mg?e:f-d;try{g.Ib(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},ira=function(a){a.Qb||a.jf||(a.D=1,a.jf=J6((0,g.x)(a.ly,a),0),a.Nh=0)},Z6=function(a){if(a.Qb||a.jf||3<=a.Nh)return!1;
a.D++;a.jf=J6((0,g.x)(a.ly,a),jra(a,a.Nh));a.Nh++;return!0},N6=function(a,b,c){a.ao=c;
a.De=b.wf;a.C||era(a)},X6=function(a){null!=a.Qg&&(g.u.clearTimeout(a.Qg),a.Qg=null)},jra=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Pc&&(c=null);var d=(0,g.x)(a.kM,a);c||(c=new g.Em("//www.google.com/images/cleardot.gif"),V5(c));Nqa(c.toString(),1E4,d)}else E6(2);kra(a,b)},kra=function(a,b){a.o=0;
a.Pc&&a.Pc.Yt(b);cra(a);bra(a)},cra=function(a){a.o=0;
a.De=-1;if(a.Pc)if(0==a.A.length&&0==a.u.length)a.Pc.Oo();else{g.db(a.A);var b=g.db(a.u);a.A.length=0;a.u.length=0;a.Pc.Oo(b)}},M6=function(a,b,c){var d=g.Mm(c);
if(""!=d.o)b&&g.Gm(d,b+"."+d.o),g.Hm(d,d.B);else{var e=window.location;d=iqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.sj&&g.Ib(a.sj,function(f,k){U5(d,k,f)});
U5(d,"VER",a.Mg);V6(a,d);return d},J6=function(a,b){if(!g.Ja(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Zqa(a7,a))},lra=function(){},mra=function(){this.o=[];
this.u=[]},nra=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.E.call(this);
this.o=new g.J(this.GK,0,this);g.H(this,this.o);this.Sc=5E3;this.u=0;if(g.Ja(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ja(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.vn;this.u=new b7(this.LL,this);this.o=null;this.bb=!1;this.B=null;this.H="";this.G=this.A=0;this.D=[];this.K=c||!1},ora=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ao,sessionId:a.o.w,arrayId:a.o.si}},pra=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&hra(a.o),dra(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},qra=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.vf(4,a))||"";b&&(this.port=":"+b);this.domain=g.wf(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Fb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Ff(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Na(a.A,d,!0),onError:g.Na(a.w,e),Nd:g.Na(a.B,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xp(b,a)},ura=function(){var a=rra;
sra();h7.push(a);tra(h7)},i7=function(a,b){sra();
var c=h7,d=vra(a,String(b));g.Ya(c)?wra(d):(tra(c),(0,g.y)(c,function(e){e(d)}))},sra=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",h7,void 0))},wra=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},tra=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},vra=function(a,b){var c=((0,g.A)()-xra)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.P.call(this);
this.D=a;this.o=[]},yra=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},zra=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Td)(a.o,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=yra(a,b[d])||c;return c},Ara=function(a,b){var c=a.o.length;
a.o=(0,g.Td)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.P.call(this);
this.C=a;this.B=b;this.w=c;this.A=d;this.u=0;this.o=null;this.Fa=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+i6(this.o))},Bra=function(a){if(a.o.length){var b=(0,g.ee)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.IC,a),(0,g.x)(a.HC,a))}},o7=function(a){var b=g6(qqa());
b=(0,g.Td)(b,function(c){return!c.uuid});
return zra(a,b)},q7=function(a,b){sqa((0,g.ee)(a.o,f6));
b&&rqa()},s7=function(a,b){g.P.call(this);
this.C=b;var c=g.jy("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Xa(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.wj(this.o))},Cra=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(Y5(b)!=Y5(a.o))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.wj(a.o)),a.o=b,a.R("screenChange"));Dra(a)},u7=function(a){isNaN(a.w)||g.xo(a.w);
a.w=g.vo((0,g.x)(a.Er,a),0<a.A&&a.A<(0,g.A)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Era=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Kb("Requesting availability of screen w/o lounge token.")});
return b},Dra=function(a){a=g.Pb(g.Jb(a.o,function(b){return b}));
g.nb(a);a.length?g.iy("yt-remote-online-screen-ids",a.join(","),60):b6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Fra(this)},Hra=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Jd();if(k=(c?l6(k,c):null)||l6(k,b)){k.uuid=b;var l=w7(a,k);Cra(a.u,l,function(m){e(m?l:null)})}else c?Gra(a,c,(0,g.x)(function(m){var n=w7(this,new d6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Cra(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},Ira=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Gra=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.xp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Jra=function(a){a.o=a.w.Jd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.o))},Fra=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.PC,a));Jra(a);a.A=g6(g.jy("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+i6(a.A));a.u=new s7(a.C,(0,g.x)(a.Jd,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.iy("yt-remote-automatic-screen-cache",(0,g.ee)(a.A,f6)));x7(a);a.B[b.uuid]=b.id;g.iy("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.jy("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.P.call(this);
this.U=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.U,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.TM,this);this.B=(0,g.x)(this.iL,this);this.A=g.vo((0,g.x)(function(){Kra(this,null)},this),12E4)},Lra=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.wj(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ea,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.wj(b))},Kra=function(a,b){g.xo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.un,a),d=(0,g.x)(a.Md,a);a.bv(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.P=c;this.B=null;this.D=g.Ea;this.C=NaN;this.K=(0,g.x)(this.WM,this);this.o=g.Ea},Mra=function(a){a.o=a.H.lA(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ea;
this.un(b)},a),(0,g.x)(function(b){this.o=g.Ea;
this.Md(b)},a))},Nra=function(a){var b={};
b.pairingCode=a.J;b.theme=a.P;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}uqa()&&(b.env_useStageMdx=1);return g.Df(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.vo((0,g.x)(this.ti,this,null),150)},D7=function(a,b,c,d){g.P.call(this);
this.u=a;this.D=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.OJ,this)},Ora=function(a,b){return b?g.Ua(a.w,function(c){return e6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},rra=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.xi(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.ky,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.ti(null)):a.R("yt-remote-cast2-session-change",null))},Pra=function(a){var b=a.u.kA(),c=a.o&&a.o.u;
a=(0,g.ee)(b,function(d){c&&e6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Ora(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Vra=function(a,b,c,d,e,f,k){Qra()?Rra(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Sra(a,c):(window.__onGCastApiAvailable=function(l,m){l?Sra(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),b6("yt-remote-cast-available"),b6("yt-remote-cast-receiver"),Tra(),c(!1))},d?g.Mo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Bqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(Aqa(),u6(Ura.map(yqa))))):H7("Cannot initialize because not running Chrome")},Tra=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);Wra(!1);g.Ho(M7);M7.length=0},N7=function(){return!!g.jy("yt-remote-cast-installed")},Xra=function(){var a=g.jy("yt-remote-cast-receiver");
return a?a.friendlyName:null},Yra=function(){H7("clearCurrentReceiver");
b6("yt-remote-cast-receiver")},Zra=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Co("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Qra=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ts||a},$ra=function(a,b){L7().init(a,b)},Rra=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.iy("yt-remote-cast-available",f);a6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.iy("yt-remote-cast-receiver",f);a6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.iy("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+h6(f));
f||b6("yt-remote-cast-receiver");a6("yt-remote-cast2-session-change",f)}),g.Da("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Sra=function(a,b){K7(!0);
I7(!1);$ra(a,function(c){c?(Wra(!0),g.Jo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),b6("yt-remote-cast-available"),b6("yt-remote-cast-receiver"),Tra());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.iy("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Wra=function(a){H7("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.D=0;this.o=null;this.hasNext=this.Ee=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Ee=!1;a.hasNext=!1;a.D=0;a.C=(0,g.A)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.A)()-a.C)/1E3:0},U7=function(a,b){a.D=b;
a.C=(0,g.A)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.A)()-a.C)/1E3+a.D;
case -1E3:return 0}return a.D},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.o);b.hasPrevious=a.Ee;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.P.call(this);
this.o=0;this.A=a;this.C=[];this.B=new mra;this.w=this.u=null;this.H=(0,g.x)(this.MH,this);this.D=(0,g.x)(this.qk,this);this.G=(0,g.x)(this.LH,this);this.J=(0,g.x)(this.YH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ds,this),asa(this))):c=3;0!=c&&(b?this.Ds(c):g.vo((0,g.x)(function(){this.Ds(c)},this),0));
var d=Zra();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},asa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Na(this.LJ,b),this))},a)},bsa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){bsa(a);
a.A.setPlayerContextData(X7(b));asa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.D),a.qk(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.D),a.w.media.length&&a.qk(a.w.media[0]))},csa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Kb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.P.call(this);
this.B=NaN;this.K=!1;this.G=this.D=this.H=this.J=NaN;this.U=[];this.A=this.C=this.w=this.Pa=this.o=null;this.T=a;this.U.push(g.Uq(window,"beforeunload",(0,g.x)(this.BC,this)));this.u=[];this.Pa=new R7;this.P=b.id;this.o=dsa(this,c);this.o.subscribe("handlerOpened",this.QH,this);this.o.subscribe("handlerClosed",this.NH,this);this.o.subscribe("handlerError",this.OH,this);this.o.subscribe("handlerMessage",this.PH,this);qra(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.GL()&&g.iy("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},dsa=function(a,b){return new c7(f7(a.T,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},esa=function(a){a.B=g.vo((0,g.x)(function(){g8("Connecting timeout");
this.Rh(1)},a),2E4)},i8=function(a){g.xo(a.B);
a.B=NaN},j8=function(a){g.xo(a.J);
a.J=NaN},fsa=function(a){k8(a);
a.H=g.vo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.xo(a.H);
a.H=NaN},hsa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Zu()&&a.Pa.reset(),h8(a,1),l8(a,"getNowPlaying"),gsa(a)):a.Rh(1)},isa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Wb(b.params)?a.Pa.o=null:a.Pa.o=b.params,a.R("remotePlayerChange"))},jsa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;W7(a.Pa,c,d);a.R("remoteQueueChange")},lsa=function(a,b){b.params=b.params||{};
jsa(a,b);ksa(a,b);a.R("autoplayDismissed")},ksa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.G=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Pa.playerState?fsa(a):k8(a);a.R("remotePlayerChange")},msa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Pa,isNaN(c)?0:c);a.R("remotePlayerChange")}},nsa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.R("remotePlayerChange")},osa=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},psa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ee="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.R("previousNextChange")},gsa=function(a){g.xo(a.G);
a.G=g.vo((0,g.x)(a.Rh,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.wj(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Rc=a;this.u=[];this.u.push(this.Rc.$_s("screenChange",(0,g.x)(this.RM,this)));this.u.push(this.Rc.$_s("onlineScreenChange",(0,g.x)(this.pJ,this)))},usa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.no("MDX_CONFIG")||b;jqa();q6();n8||(n8=new e7(b?b.loungeApiHost:void 0),uqa()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",o8,void 0));qsa();var c=p8();if(!c){var d=new v7(n8);g.Da("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Vra(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){a6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Da("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.wj(b)),s8.push(g.Co("yt-remote-cast2-availability-change",function(){a6("yt-remote-receiver-availability-change")})),s8.push(g.Co("yt-remote-cast2-receiver-selected",function(){t8(null);
a6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Co("yt-remote-cast2-receiver-resumed",function(){a6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Co("yt-remote-cast2-session-change",rsa)),s8.push(g.Co("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Yra())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.op("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.wj(a)),ssa(a),c.start(),q8()||tsa())},wsa=function(){var a=vsa();
N7()&&g.jy("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},vsa=function(){var a=p8().Rc.$_gos();
var b=w8();b&&x8()&&(k6(a,b)||a.push(b));return oqa(a)},y8=function(){var a=xsa();
!a&&N7()&&Xra()&&(a={key:"cast-selector-receiver",name:Xra()});return a},xsa=function(){var a=vsa(),b=w8();
b||(b=u8());return g.Ua(a,function(c){return b&&e6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().Jd();return l6(b,a)},rsa=function(a){r8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},ysa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},zsa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||ysa("");g.Da("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?a6("yt-remote-connection-change",!1):!b&&a&&a6("yt-remote-connection-change",!0)},u8=function(){var a=g.GL();
if(!a)return null;var b=p8().Jd();return l6(b,a)},A8=function(a,b){w8()&&w8();
if(E8)F8=a;else{ysa(a.id);var c=new f8(n8,a,v8());c.connect(b,zsa());c.subscribe("beforeDisconnect",function(d){a6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&B8(null)});
B8(c)}},tsa=function(){var a=u8();
a?(r8("Resume connection to: "+h6(a)),A8(a,0)):(s6(),Yra(),r8("Skipping connecting because no session screen found."))},qsa=function(){var a=v8();
if(g.Wb(a)){a=p6();var b=g.jy("yt-remote-session-name")||"",c=g.jy("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},ssa=function(a){a?(g.iy("yt-remote-session-app",a.app),g.iy("yt-remote-session-name",a.name)):(b6("yt-remote-session-app"),b6("yt-remote-session-name"));
g.Da("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.E.call(this);
this.B=a;this.u=b;this.w=new g.Q(this);g.H(this,this.w);this.w.M(b,"onCaptionsTrackListChanged",this.KI);this.w.M(b,"captionschanged",this.KH);this.w.M(b,"captionssettingschanged",this.xz);this.w.M(b,"videoplayerreset",this.vn);this.w.M(b,"mdxautoplaycancel",this.vB);this.T=this.w.M(b,"onVolumeChange",this.Rx);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.gy,this);c.subscribe("remotePlayerChange",this.tk,this);c.subscribe("remoteQueueChange",this.vn,this);c.subscribe("autoplayUpNext",this.Hx,
this);c.subscribe("previousNextChange",this.dy,this);c.subscribe("nowAutoplaying",this.Yx,this);c.subscribe("autoplayDismissed",this.Gx,this);this.suggestion=null;this.H=new g.Mt(64);this.A=new g.J(this.vz,500,this);g.H(this,this.A);this.C=new g.J(this.wz,1E3,this);g.H(this,this.C);this.K=new w6(this.tM,0,this);g.H(this,this.K);this.D={};this.U=new g.J(this.Xz,1E3,this);g.H(this,this.U);this.J=new g.el(this.eF,1E3,this);g.H(this,this.J);this.P=g.Ea;this.xz();this.vn();this.tk()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.U=b||0;c.player.R("progresssync",b,d)},Asa=function(a){H8(a,0);
a.A.stop();I8(a,new g.Mt(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.bc(c,b));a.o.kz(a.u.getVideoData(1).videoId,c);a.D=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Ge,X5(c));I8(a,new g.Mt(1))},Bsa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{GQ:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.St(c,b)){var d=g.T(b,2);d!=g.T(a.H,2)&&g.NS(a.u.app,d);a.H=b;Csa(a.B,c,b)}},M8=function(){g.W.call(this,{F:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},L:[{F:"div",I:"ytp-mdx-popup-dialog-inner-content",L:[{F:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{F:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{F:"div",I:"ytp-mdx-privacy-popup-buttons",L:[{F:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{F:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.w=new g.ML(this,250);g.H(this,this.w);this.D=this.u["ytp-mdx-privacy-popup-cancel"];this.M(this.D,"click",this.A);this.B=this.u["ytp-mdx-privacy-popup-confirm"];this.M(this.B,"click",this.C)},N8=function(a){g.W.call(this,{F:"div",
I:"ytp-remote",L:[{F:"div",I:"ytp-remote-display-status",L:[{F:"div",I:"ytp-remote-display-status-icon",L:[g.OL()]},{F:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.w=new g.ML(this,250);g.H(this,this.w);this.A=a;this.M(a,"presentingplayerstatechange",this.B);Dsa(this,g.BK(a))},Dsa=function(a,b){if(3==a.A.getPresentingPlayerType()){var c={RECEIVER_NAME:a.A.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.sM("Error on $RECEIVER_NAME",c):g.Tt(b)||g.T(b,4)?g.sM("Playing on $RECEIVER_NAME",c):g.sM("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.w.show()}else a.w.hide()},O8=function(a,b){g.oO.call(this,"Play on",0,a,b);
this.w=a;this.D={};this.M(a,"onMdxReceiversChange",this.K);this.M(a,"presentingplayerstatechange",this.K);this.K()},P8=function(a){g.xP.call(this,a);
this.u={key:j6(),name:"This computer"};this.B=null;this.A=[];this.P=this.o=null;this.J=[this.u];this.w=this.u;this.D=new g.Mt(64);this.U=0;this.H=-1;this.C=null;if(!g.lz(this.player.O())){a=this.player;var b=g.dD(a);b&&(b=b.dk())&&(b=new O8(a,b),g.H(this,b));b=new N8(a);g.H(this,b);g.UK(a,b.element,4);this.C=new M8;g.H(this,this.C);g.UK(a,this.C.element,4);this.K=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Csa=function(a,b,c){a.D=
c;
a.player.R("presentingplayerstatechange",new g.uD(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.no("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.no("SESSION_INDEX")&&!g.no("LOGGED_IN")))||a.K||!a.C);if(c?0:a.player.O().eh()||"WEB_EMBEDDED_PLAYER"==a.player.O().deviceParams.c)g.Tt(g.BK(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.nL,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.w.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ge,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=X5(c))&&(d.locationInfo=c);c=d}else c=null;r8("Connecting to: "+g.wj(b));"cast-selector-receiver"==b.key?(t8(c||null),O7()?L7().setLaunchParams(c||null):J7("setLaunchParams called before ready.")):
!c&&C8()&&q8()==b.key?a6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().Jd(),(c=l6(c,b.key))&&A8(c,1))}},Kqa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},Esa={},mqa={uN:"atp",QP:"ska",FP:"que",gP:"mus",PP:"sus",uO:"dsp",MP:"seq"};
c6.prototype.ag=function(){var a=new c6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var t6,o6="",zqa=vqa("loadCastFramework")||vqa("loadCastApplicationFramework"),Ura=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Pa(w6,g.E);g.h=w6.prototype;g.h.xC=function(a){this.A=arguments;this.o=!1;this.Fa?this.w=(0,g.A)()+this.Sc:this.Fa=g.cl(this.B,this.Sc)};
g.h.stop=function(){this.Fa&&(g.u.clearTimeout(this.Fa),this.Fa=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.Y=function(){this.stop();w6.xb.Y.call(this)};
g.h.yC=function(){this.w?(this.Fa=g.cl(this.B,this.w-(0,g.A)()),this.w=null):(this.Fa=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};y6.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Dqa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Pa(Cqa,z6);S8=new Cqa;g.h=A6.prototype;g.h.Yg=null;g.h.oe=!1;g.h.Zi=null;g.h.As=null;g.h.Ki=null;g.h.fi=null;g.h.Vf=null;g.h.Bg=null;g.h.uh=null;g.h.uc=null;g.h.Tk=0;g.h.ue=null;g.h.co=null;g.h.lg=null;g.h.Gj=-1;g.h.fz=!0;g.h.Lg=!1;g.h.Ap=0;g.h.An=null;var Iqa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.AL=function(a){a=a.target;var b=this.An;b&&3==R6(a)?b.lm():this.fA(a)};
g.h.fA=function(a){try{if(a==this.uc)a:{var b=R6(this.uc),c=this.uc.C,d=this.uc.getStatus();if(g.Gd&&!g.kd(10)||g.Id&&!g.jd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.dg&&!T6(this.uc))break a;this.Lg||4!=b||7==c||(8==c||0>=d?this.o.ne(3):this.o.ne(2));K6(this);var e=this.uc.getStatus();this.Gj=e;var f=T6(this.uc);(this.oe=200==e)?(4==b&&G6(this),this.C?(Jqa(this,b,f),g.dg&&this.oe&&3==b&&(this.A.ga(this.u,"tick",this.tL),this.u.start())):F6(this,f),this.oe&&!this.Lg&&(4==b?this.o.sn(this):(this.oe=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.lg=3,E6(13)):(this.lg=0,E6(14)),G6(this),H6(this))}}catch(k){this.uc&&T6(this.uc)}finally{}};
g.h.tL=function(){var a=R6(this.uc),b=T6(this.uc);this.Tk<b.length&&(K6(this),Jqa(this,a,b),this.oe&&4!=a&&C6(this))};
g.h.PK=function(a){J6((0,g.x)(this.OK,this,a),0)};
g.h.OK=function(a){this.Lg||(K6(this),F6(this,a),C6(this))};
g.h.ny=function(a){J6((0,g.x)(this.NK,this,a),0)};
g.h.NK=function(a){this.Lg||(G6(this),this.oe=a,this.o.sn(this),this.o.ne(4))};
g.h.cancel=function(){this.Lg=!0;G6(this)};
g.h.XK=function(){this.Zi=null;var a=(0,g.A)();0<=a-this.As?(2!=this.fi&&this.o.ne(3),G6(this),this.lg=2,E6(18),H6(this)):Mqa(this,this.As-a)};
g.h.getLastError=function(){return this.lg};g.h=Pqa.prototype;g.h.yp=null;g.h.yd=null;g.h.Bn=!1;g.h.jv=null;g.h.Ul=null;g.h.bq=null;g.h.zp=null;g.h.ae=null;g.h.wf=-1;g.h.Fj=null;g.h.hj=null;g.h.connect=function(a){this.zp=a;a=M6(this.o,null,this.zp);E6(3);this.jv=(0,g.A)();var b=this.o.G;null!=b?(this.Fj=b[0],(this.hj=b[1])?(this.ae=1,Qqa(this)):(this.ae=2,O6(this))):(W5(a,"MODE","init"),this.yd=new A6(this,void 0,void 0,void 0),this.yd.Yg=this.yp,B6(this.yd,a,!1,null,!0),this.ae=0)};
g.h.wB=function(a){if(a)this.ae=2,O6(this);else{E6(4);var b=this.o;b.De=b.Zf.wf;$6(b,9)}a&&this.ne(2)};
g.h.Uo=function(a){return this.o.Uo(a)};
g.h.abort=function(){this.yd&&(this.yd.cancel(),this.yd=null);this.wf=-1};
g.h.hv=function(){return!1};
g.h.hy=function(a,b){this.wf=a.Gj;if(0==this.ae)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.De=this.wf;$6(c,2);return}this.Fj=c[0];this.hj=c[1]}else c=this.o,c.De=this.wf,$6(c,2);else if(2==this.ae)if(this.Bn)E6(7),this.bq=(0,g.A)();else if("11111"==b){if(E6(6),this.Bn=!0,this.Ul=(0,g.A)(),c=this.Ul-this.jv,!g.Gd||g.kd(10)||500>c)this.wf=200,this.yd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Ul=this.bq=(0,g.A)(),this.Bn=!1};
g.h.sn=function(){this.wf=this.yd.Gj;if(this.yd.oe)0==this.ae?this.hj?(this.ae=1,Qqa(this)):(this.ae=2,O6(this)):2==this.ae&&((!g.Gd||g.kd(10)?!this.Bn:200>this.bq-this.Ul)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.ae?E6(9):2==this.ae&&E6(10);var a=this.o;this.yd.getLastError();a.De=this.wf;$6(a,2)}};
g.h.Ik=function(){return this.o.Ik()};
g.h.isActive=function(){return this.o.isActive()};
g.h.ne=function(a){this.o.ne(a)};g.Pa(P6,g.rk);var Vqa=/^https?$/i,Fsa=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.Z=b;this.T=!1;this.w=!0;this.o=this.P?Eqa(this.P):Eqa(S8);this.U=this.P?this.P.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.kv,this);try{$5(S6(this,"Opening Xhr")),this.da=!0,this.o.open(b,String(a),!0),this.da=!1}catch(f){$5(S6(this,"Error opening Xhr: "+f.message));Uqa(this,f);return}a=c||
"";var e=this.headers.clone();d&&hqa(d,function(f,k){e.set(k,f)});
d=g.Ua(e.Xd(),Sqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.Xa(Fsa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.aa&&(this.o.responseType=this.aa);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{Xqa(this),0<this.D&&(this.K=Rqa(this.o),$5(S6(this,"Will abort after "+this.D+"ms if incomplete, xhr2 "+this.K)),this.K?(this.o.timeout=this.D,this.o.ontimeout=(0,g.x)(this.lv,this)):this.J=g.cl(this.lv,this.D,this)),$5(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){$5(S6(this,"Send error: "+f.message)),Uqa(this,f)}};
g.h.lv=function(){"undefined"!=typeof g.k_&&this.o&&(this.A="Timed out after "+this.D+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.Y=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.xb.Y.call(this)};
g.h.kv=function(){this.ha()||(this.da||this.G||this.B?Wqa(this):this.NJ())};
g.h.NJ=function(){Wqa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.sj=null;g.h.sd=null;g.h.Qb=null;g.h.xp=null;g.h.Wl=null;g.h.Mt=null;g.h.mm=null;g.h.mk=0;g.h.eH=0;g.h.Pc=null;g.h.gg=null;g.h.jf=null;g.h.Qg=null;g.h.Zf=null;g.h.ao=null;g.h.si=-1;g.h.Tv=-1;g.h.De=-1;g.h.Th=0;g.h.Nh=0;g.h.Mg=8;var a7=new g.rk;g.Pa(Zqa,g.Tj);g.Pa($qa,g.Tj);g.Pa(ara,g.Tj);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.xp=b;this.sj=c||{};d&&void 0!==e&&(this.sj.OSID=d,this.sj.OAID=e);this.C?(J6((0,g.x)(this.gu,this,a),100),era(this)):this.gu(a)};
g.h.gu=function(a){this.Zf=new Pqa(this);this.Zf.yp=null;this.Zf.u=this.B;this.Zf.connect(a)};
g.h.hv=function(){return 0==this.o};
g.h.my=function(a){this.gg=null;hra(this,a)};
g.h.ly=function(){this.jf=null;this.Qb=new A6(this,this.w,"rpc",this.D);this.Qb.Yg=null;this.Qb.Ap=0;var a=this.Mt.clone();U5(a,"RID","rpc");U5(a,"SID",this.w);U5(a,"CI",this.ao?"0":"1");U5(a,"AID",this.si);V6(this,a);if(!g.Gd||g.kd(10))U5(a,"TYPE","xmlhttp"),B6(this.Qb,a,!0,this.mm,!1);else{U5(a,"TYPE","html");var b=this.Qb,c=!!this.mm;b.fi=3;b.Vf=V5(a.clone());Lqa(b,c)}};
g.h.hy=function(a,b){if(0!=this.o&&(this.Qb==a||this.sd==a))if(this.De=a.Gj,this.sd==a&&3==this.o)if(7<this.Mg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ha(c)&&3==c.length)if(0==c[0])a:{if(!this.jf){if(this.Qb)if(this.Qb.Ki+3E3<this.sd.Ki)X6(this),this.Qb.cancel(),this.Qb=null;else break a;Z6(this);E6(19)}}else this.Tv=c[1],0<this.Tv-this.si&&37500>c[2]&&this.ao&&0==this.Nh&&!this.Qg&&(this.Qg=J6((0,g.x)(this.GH,this),6E3));else $6(this,11)}else b!=Esa.SN.o&&$6(this,11);else if(this.Qb==a&&
X6(this),!g.tb(b)){c=this.B.parse(b);g.Ha(c);for(var d=0;d<c.length;d++){var e=c[d];this.si=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.mm=e[2],e=e[3],null!=e?this.Mg=e:this.Mg=6,this.o=3,this.Pc&&this.Pc.au(),this.Mt=M6(this,this.Ik()?this.mm:null,this.xp),ira(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Pc&&this.Pc.Zt(e),this.Nh=0)}}};
g.h.GH=function(){null!=this.Qg&&(this.Qg=null,this.Qb.cancel(),this.Qb=null,Z6(this),E6(20))};
g.h.sn=function(a){if(this.Qb==a){X6(this);this.Qb=null;var b=2}else if(this.sd==a)this.sd=null,b=1;else return;this.De=a.Gj;if(0!=this.o)if(a.oe)1==b?(b=(0,g.A)()-a.Ki,a7.dispatchEvent(new $qa(a7,a.uh?a.uh.length:0,b,this.Th)),W6(this),this.A.length=0):ira(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.De)){if(d=1==b)this.sd||this.gg||1==this.o||2<=this.Th?d=!1:(this.gg=J6((0,g.x)(this.my,this,a),jra(this,this.Th)),this.Th++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.RB=function(a){if(!g.Xa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.kM=function(a){a?E6(2):(E6(1),kra(this,8))};
g.h.Uo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.V=!1;return a};
g.h.isActive=function(){return!!this.Pc&&this.Pc.isActive(this)};
g.h.ne=function(a){a7.dispatchEvent(new ara(a7,a))};
g.h.Ik=function(){return!(!g.Gd||g.kd(10))};
g.h=lra.prototype;g.h.au=function(){};
g.h.Zt=function(){};
g.h.Yt=function(){};
g.h.Oo=function(){};
g.h.Ju=function(){return{}};
g.h.isActive=function(){return!0};g.h=mra.prototype;g.h.isEmpty=function(){return g.Ya(this.o)&&g.Ya(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.Xa(this.o,a)||g.Xa(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Tna)(b,a);0<=c?(g.$a(b,c),b=!0):b=!1;return b||g.ab(this.u,a)};
g.h.nd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Pa(b7,g.E);g.h=b7.prototype;g.h.GK=function(){this.Sc=Math.min(3E5,2*this.Sc);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Sc+15E3*Math.random();g.Xm(this.o,a);this.u=(0,g.A)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Sc=5E3};g.Pa(c7,lra);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Gf=function(a){return this.w.Zg(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.bb||(this.bb=!0,g.xi(this.w),pra(this),g.xi(this.u),this.u=null)};
g.h.ha=function(){return this.bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.o;e&&(e.Pc=null);d.Pc=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.si):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.D.push(c):d7(this)&&fra(this.o,c)};
g.h.au=function(){this.u.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)fra(this.o,a[b])}this.R("handlerOpened")};
g.h.Yt=function(a){var b=2==a&&401==this.o.De;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.Oo=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Ju=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.bc(a,this.B);return a};
g.h.Zt=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),dra(this.o)):this.R("handlerMessage",new nra(a[0],a[1]))};
g.h.LL=function(){this.u.isActive();var a=this.o,b=0;a.Qb&&b++;a.sd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var xra=(0,g.A)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Pa(m7,g.P);m7.prototype.Jd=function(){return this.o};
m7.prototype.contains=function(a){return!!k6(this.o,a)};
m7.prototype.get=function(a){return a?l6(this.o,a):null};
m7.prototype.info=function(a){i7(this.D,a)};g.r(n7,g.P);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Fa)&&this.jA()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Fa)||(g.xo(this.Fa),this.Fa=NaN)};
g.h.Y=function(){this.stop();g.P.prototype.Y.call(this)};
g.h.jA=function(){this.Fa=NaN;this.o=g.xp(f7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.PM,this),onError:(0,g.x)(this.OM,this),Nd:(0,g.x)(this.QM,this)})};
g.h.PM=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.w;c.name=this.A;this.R("pairingComplete",new d6(c))};
g.h.OM=function(a){this.o=null;a.status&&404==a.status?this.u>=Gsa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=Gsa[this.u],this.Fa=g.vo((0,g.x)(this.jA,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.QM=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var Gsa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Pa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.jy("yt-remote-lounge-token-expiration")&&Bra(this);g.xo(this.u);this.u=g.vo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);yra(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||Bra(this)};
g.h.remove=function(a,b){var c=o7(this);Ara(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Xn=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.Y=function(){g.xo(this.u);p7.xb.Y.call(this)};
g.h.IC=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.D,"Missed "+b+" lounge tokens.")};
g.h.HC=function(a){i7(this.D,"Requesting lounge tokens failed: "+a)};g.r(s7,g.P);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.jy("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.A)()-144E5<a?0:a)?u7(this):(this.A=(0,g.A)()+3E5,g.iy("yt-remote-fast-check-period",this.A),this.Er())};
g.h.isEmpty=function(){return g.Wb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.o,function(c,d){return c&&!!l6(a,d)},this);
t7(this,b)};
g.h.Y=function(){g.xo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.P.prototype.Y.call(this)};
g.h.Er=function(){g.xo(this.w);this.w=NaN;this.u&&this.u.abort();var a=Era(this);if(Y5(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Pb(a).join(",")},(0,g.x)(this.jK,this,a),(0,g.x)(this.iK,this))}else t7(this,{}),u7(this)};
g.h.jK=function(a,b){this.u=null;var c=g.Pb(Era(this));if(g.ob(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Kb("Changing Screen set during request."),this.Er()};
g.h.iK=function(a){this.Kb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Kb=function(a){i7("OnlineScreenService",a)};g.Pa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Xn=function(a,b,c,d){this.w.contains(a)?this.w.Xn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.D,a),d(Error(a)))};
g.h.Jd=function(a){return a?this.o:g.cb(this.o,(0,g.Td)(this.A,function(b){return!this.contains(b)},this))};
g.h.kA=function(){return(0,g.Td)(this.Jd(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.lA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.xi(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.xi(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.SM=function(a,b,c,d){g.xp(f7(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new d6(f.screen||{});if(!k.name||Ira(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Ira(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.xi(this.w);g.xi(this.u);v7.xb.Y.call(this)};
g.h.PC=function(){Jra(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Pa(y7,g.P);g.h=y7.prototype;g.h.un=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.Md=function(a){this.ha()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.U,a)};
g.h.nA=function(){return null};
g.h.Mr=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Mr("");y7.xb.Y.call(this)};g.Pa(A7,y7);g.h=A7.prototype;g.h.Lr=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Lra(this)};
g.h.ti=function(a){this.info("launchWithParams no-op for Cast: "+g.wj(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.Mr=g.Ea;g.h.Y=function(){this.info("disposeInternal");g.xo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.xb.Y.call(this)};
g.h.iL=function(a,b){if(!this.ha())if(b){var c=x6(b);if(g.Ka(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.wj(c));switch(d){case "mdxSessionStatus":Kra(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.bv=function(a,b,c,d){Hra(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.vo((0,g.x)(this.bv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.nA=function(){return this.o};
g.h.TM=function(a){this.ha()||a||(z7(this,"Cast session died."),this.Md())};g.Pa(B7,y7);g.h=B7.prototype;g.h.Lr=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.ti=function(a){this.B=a;this.D()};
g.h.stop=function(){this.o();this.o=g.Ea;g.xo(this.C);this.A?this.A.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.Y=function(){this.o();this.o=g.Ea;g.xo(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;B7.xb.Y.call(this)};
g.h.WM=function(a){this.ha()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ea,this.Md())};
g.h.Mp=function(a){this.J=j6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Nra(this));a(b);Mra(this)}else this.D=(0,g.x)(function(){g.xo(this.C);this.D=g.Ea;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Nra(this));a(c);Mra(this)},this),this.C=g.vo((0,g.x)(function(){this.D()},this),100)};
g.h.jD=function(a,b,c){Hra(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.un(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Mp(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Mp(b,c)},this))};g.Pa(C7,y7);C7.prototype.stop=function(){this.Md()};
C7.prototype.Lr=g.Ea;C7.prototype.ti=function(){g.xo(this.o);this.o=NaN;var a=l6(this.H.Jd(),this.u.label);a?this.un(a):this.Md(Error("No such screen"))};
C7.prototype.Y=function(){g.xo(this.o);this.o=NaN;C7.xb.Y.call(this)};g.Pa(D7,g.P);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.SJ,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.jy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.fI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.A),ura(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.mA,this)),this.w=Pra(this),chrome.cast.setCustomReceivers(this.w,g.Ea,(0,g.x)(function(k){this.Kb("Failed to set initial custom receivers: "+g.wj(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Kb("Failed to initialize API: "+g.wj(k));
b(!1)},this))};
g.h.TL=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=l6(this.u.Jd(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Ora(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ea,(0,g.x)(function(e){this.Kb("Failed to set initial custom receivers: "+g.wj(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Mr(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.UL=function(a){this.ha()?this.Kb("Setting connection data on disposed cast v2"):this.o?this.o.ti(a):this.Kb("Setting connection data without a session")};
g.h.VM=function(){this.ha()?this.Kb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.jy,this),(0,g.x)(this.pK,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.mA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);g.ab(g.w("yt.mdx.remote.debug.handlers_")||[],rra);g.xi(this.o);D7.xb.Y.call(this)};
g.h.Kb=function(a){i7("Controller",a)};
g.h.ky=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.OJ=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Kb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Kb("Stopping receiver w/o session: "+a.friendlyName)}else this.Kb("onReceiverAction_ called without receiver.")};
g.h.fI=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Kb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.jD,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Mp,b))};
g.h.jy=function(a){if(!this.ha()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Kb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=l6(this.u.Jd(),c.label);d&&e6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.xi(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.ky,this,this.o)),this.o.ti(null));this.o.Lr(a)}}};
g.h.UM=function(){return this.o?this.o.nA():null};
g.h.pK=function(a){this.ha()||(this.Kb("Failed to estabilish a session: "+g.wj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.SJ=function(a){E7("Receiver availability updated: "+a);if(!this.ha()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.mA=function(){this.ha()||(this.w=Pra(this),E7("Updating custom receivers: "+g.wj(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ea,(0,g.x)(function(){this.Kb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.UL;D7.prototype.setConnectedScreenStatus=D7.prototype.TL;D7.prototype.stopSession=D7.prototype.VM;D7.prototype.getCastSession=D7.prototype.UM;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Ee=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.P);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ea,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ea,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ea,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Na(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ea,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Kb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Kb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Na(this.setVolume,a,b))};
g.h.kz=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.wj(b.style),g.bc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Na(this.kz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Na(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.wj(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.iA=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Na(this.iA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Na(this.nextVideo,a,b))};
g.h.nu=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.nu)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.P.prototype.dispose.call(this)};
g.h.Y=function(){bsa(this);this.A=null;this.B.clear();Y7(this,null);g.P.prototype.Y.call(this)};
g.h.Ds=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.Ya(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.LJ=function(a,b){this.R(a,b)};
g.h.MH=function(a){if(!a)this.qk(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.qk=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),csa(this),this.R("remotePlayerChange")};
g.h.LH=function(a){a?(csa(this),this.R("remotePlayerChange")):this.qk(null)};
g.h.YH=function(){var a=Zra();a&&Y7(this,a)};
g.h.Kb=function(a){i7("CP",a)};g.r(f8,g.P);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;U7(this.Pa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.wj(l));this.o.connect({method:"setPlaylist",
params:g.wj(l)},a,r6())}else g8("Connecting without params"),this.o.connect({},a,r6());esa(this)};
g.h.dispose=function(){this.ha()||(this.R("beforeDispose"),h8(this,3));g.P.prototype.dispose.call(this)};
g.h.Y=function(){i8(this);k8(this);j8(this);g.xo(this.D);this.D=NaN;g.xo(this.G);this.G=NaN;this.w=null;g.Vq(this.U);this.U.length=0;this.o.dispose();g.P.prototype.Y.call(this);this.A=this.C=this.u=this.Pa=this.o=null};
g.h.BC=function(){this.Rh(2)};
g.h.QH=function(){g8("Channel opened");this.K&&(this.K=!1,j8(this),this.J=g.vo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.Rh(1)},this),15E3));
tqa(ora(this.o),this.P)};
g.h.NH=function(){g8("Channel closed");isNaN(this.B)?s6(!0):s6();this.dispose()};
g.h.OH=function(a){s6();isNaN(this.Aj())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.K=!0,g8("Channel error: "+a+" with reconnection in "+this.Aj()+" ms"),h8(this,2))};
g.h.PH=function(a){a.params?g8("Received: action="+a.action+", params="+g.wj(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.ee)(a,function(c){return new c6(c)});
a=!!g.Ua(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
hsa(this,a);break;case "loungeScreenDisconnected":g.bb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
hsa(this,!1);break;case "remoteConnected":var b=new c6(x6(a.params.device));g.Ua(this.u,function(c){return b?c.id==b.id:!1})||eqa(this.u,b);
break;case "remoteDisconnected":b=new c6(x6(a.params.device));g.bb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":jsa(this,a);break;case "nowPlaying":lsa(this,a);break;case "onStateChange":ksa(this,a);break;case "onAdStateChange":msa(this,a);break;case "onVolumeChanged":nsa(this,a);break;case "onSubtitlesTrackChanged":isa(this,a);break;case "nowAutoplaying":osa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":psa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.IL=function(){if(this.w){var a=this.w;this.w=null;this.Pa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.qC=function(){var a=3;this.ha()||(a=0,isNaN(this.Aj())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Rh=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&s6();pra(this.o,a);this.dispose()};
g.h.pC=function(){var a=this.Pa;this.w&&(a=this.Pa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.VL=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.w=b.videoId,g.xo(this.D),this.D=g.vo((0,g.x)(this.IL,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&V7(this.Pa)==V7(b)&&g.wj(this.Pa.o)==g.wj(b.o)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.y)(c,function(d){this.R(d)},this)};
g.h.Zu=function(){var a=this.o.C.id,b=g.Ua(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Aj=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.A)():NaN};
g.h.eC=function(){return this.A||"UNSUPPORTED"};
g.h.fC=function(){return this.C||""};
g.h.MM=function(){if(!isNaN(this.Aj())){var a=this.o.u;g.Ym(a.o);a.start()}};
g.h.QL=function(a,b){l8(this,a,b);gsa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Gf;f8.prototype.getProxyState=f8.prototype.qC;f8.prototype.disconnect=f8.prototype.Rh;f8.prototype.getPlayerContextData=f8.prototype.pC;f8.prototype.setPlayerContextData=f8.prototype.VL;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Zu;f8.prototype.getReconnectTimeout=f8.prototype.Aj;f8.prototype.getAutoplayMode=f8.prototype.eC;f8.prototype.getAutoplayVideoId=f8.prototype.fC;f8.prototype.reconnect=f8.prototype.MM;
f8.prototype.sendMessage=f8.prototype.QL;g.r(m8,m7);g.h=m8.prototype;g.h.Jd=function(a){return this.Rc.$_gs(a)};
g.h.contains=function(a){return!!this.Rc.$_c(a)};
g.h.get=function(a){return this.Rc.$_g(a)};
g.h.start=function(){this.Rc.$_st()};
g.h.add=function(a,b,c){this.Rc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Rc.$_r(a,b,c)};
g.h.Xn=function(a,b,c,d){this.Rc.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.u.length;a<b;++a)this.Rc.$_ubk(this.u[a]);this.u.length=0;this.Rc=null;m7.prototype.Y.call(this)};
g.h.RM=function(){this.R("screenChange")};
g.h.pJ=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.SM;v7.prototype.$_gsppc=v7.prototype.lA;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Xn;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Jd;v7.prototype.$_gos=v7.prototype.kA;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Gf;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.E);g.h=G8.prototype;
g.h.Y=function(){g.E.prototype.Y.call(this);this.A.stop();this.C.stop();this.K.stop();this.P();this.o.unsubscribe("proxyStateChange",this.gy,this);this.o.unsubscribe("remotePlayerChange",this.tk,this);this.o.unsubscribe("remoteQueueChange",this.vn,this);this.o.unsubscribe("autoplayUpNext",this.Hx,this);this.o.unsubscribe("previousNextChange",this.dy,this);this.o.unsubscribe("nowAutoplaying",this.Yx,this);this.o.unsubscribe("autoplayDismissed",this.Gx,this);this.o=this.B=null};
g.h.Dw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.lm(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.KH=function(a){this.K.xC(a)};
g.h.tM=function(a){this.Dw("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.xz=function(){var a=this.u.getOption("captions","track");g.Wb(a)||K8(this,a)};
g.h.Rx=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.tk,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.U.start();this.o.subscribe("remotePlayerChange",this.tk,this)}};
g.h.KI=function(){g.Wb(this.D)||Bsa(this,this.D);this.G=!1};
g.h.gy=function(a,b){this.C.stop();2==b&&this.wz()};
g.h.tk=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.Mt(8));this.vz();break;case 1085:case 3:I8(this,new g.Mt(9));break;case 1083:case 0:I8(this,new g.Mt(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.Mt(4));break;case 2:I8(this,new g.Mt(4));H8(this,V7(a));
break;case -1:I8(this,new g.Mt(64));break;case -1E3:I8(this,new g.Mt(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,Bsa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.U.isActive()||this.Xz()}else Asa(this)};
g.h.dy=function(){this.u.R("mdxpreviousnextchange")};
g.h.vn=function(){J8(this)||Asa(this)};
g.h.vB=function(){this.o.nu()};
g.h.Hx=function(a){a&&!g.R(this.u.O().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.xp("/watch_queue_ajax",{method:"GET",pd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.RK,this)}))&&(this.P=(0,g.x)(a.abort,a))};
g.h.RK=function(a,b){var c=new g.XB(this.u.O(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.u.R("mdxautoplayupnext",c)};
g.h.Yx=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.Gx=function(){this.u.R("mdxautoplaycanceled")};
g.h.eF=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.Xz=function(){if(J8(this)){var a=$7(this.o);this.w.Ta(this.T);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.T=this.w.M(this.u,"onVolumeChange",this.Rx)}};
g.h.vz=function(){this.A.stop();if(!this.o.ha()){var a=$7(this.o);1==a.playerState&&I8(this,new g.Mt(8));H8(this,V7(a));this.A.start()}};
g.h.wz=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.W);M8.prototype.A=function(){a6("mdx-privacy-popup-cancel");this.w.hide()};
M8.prototype.C=function(){a6("mdx-privacy-popup-confirm");this.w.hide()};g.r(N8,g.W);N8.prototype.B=function(a){Dsa(this,a.state)};g.r(O8,g.oO);O8.prototype.K=function(){var a=this.w.getOption("remote","receivers");a&&1<a.length&&!this.w.getOption("remote","quickCast")?(this.D=g.qb(a,this.C,this),g.qO(this,(0,g.ee)(a,this.C)),a=this.w.getOption("remote","currentReceiver"),this.de(this.C(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.C=function(a){return a.key};
O8.prototype.le=function(a){return"cast-selector-receiver"==a?"Cast...":this.D[a].name};
O8.prototype.Jc=function(a){g.oO.prototype.Jc.call(this,a);this.w.setOption("remote","currentReceiver",this.D[a]);this.A.ib()};g.r(P8,g.xP);g.h=P8.prototype;
g.h.create=function(){usa(g.cz(this.player.O()));this.A.push(g.Co("yt-remote-before-disconnect",this.HH,this));this.A.push(g.Co("yt-remote-connection-change",this.TJ,this));this.A.push(g.Co("yt-remote-receiver-availability-change",this.ey,this));this.A.push(g.Co("yt-remote-auto-connect",this.RJ,this));this.A.push(g.Co("yt-remote-receiver-resumed",this.QJ,this));this.A.push(g.Co("mdx-privacy-popup-confirm",this.wL,this));this.A.push(g.Co("mdx-privacy-popup-cancel",this.vL,this));this.ey()};
g.h.load=function(){this.player.cancelPlayback();g.xP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=zsa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.U=a||0,this.player.R("progresssync",a,void 0));Csa(this,this.D,this.D);g.TS(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.Ai(this.B,this.o);this.o=this.B=null;g.xP.prototype.unload.call(this);g.TS(this.player.app,5);Q8(this)};
g.h.Y=function(){g.Ho(this.A);g.xP.prototype.Y.call(this)};
g.h.bk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Dw.apply(this.B,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.H};
g.h.sC=function(){return this.loaded?this.B.suggestion:null};
g.h.Ee=function(){return this.o?$7(this.o).Ee:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.U};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.oc():!a.isAdPlaying()&&this.player.oc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.SE=function(){this.o&&this.o.iA()};
g.h.HH=function(a){1==a&&(this.P=this.o?$7(this.o):null)};
g.h.TJ=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.P=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.xi(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.P)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.ey=function(){this.J=[this.u].concat(wsa());var a=y8()||this.u;R8(this,a);this.player.ka("onMdxReceiversChange")};
g.h.nL=function(a){!this.K&&g.wD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.RJ=function(){var a=y8();R8(this,a)};
g.h.QJ=function(){this.w=y8()};
g.h.wL=function(){this.K=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.vL=function(){this.K=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.TE=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.We=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.MP.remote=P8;})(_yt_player);
